var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/fuel-comparison-calculator/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00cy1d0._.js")
R.c("server/chunks/ssr/_1ro40cv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_4rr8j.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xal6c0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qdrf8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_fuel-comparison-calculator_page_actions_1n525ul.js")
R.m(86855)
module.exports=R.m(86855).exports
