// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/brand/[brandSlug]" | "/brand/[brandSlug]/[modelSlug]" | "/brand/[brandSlug]/[modelSlug]/photos" | "/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]" | "/brands" | "/car-affordability-calculator" | "/car-loan-emi-calculator" | "/compare-cars" | "/compare/[comparisonSlug]" | "/down-payment-calculator" | "/electric-cars" | "/ev-charging-time-calculator" | "/fuel-comparison-calculator" | "/fuel-price" | "/fuel-price/[citySlug]" | "/maintenance" | "/mileage-calculator" | "/new-cars" | "/new-cars/[bodyType]" | "/news/[categorySlug]" | "/news/[categorySlug]/[articleSlug]" | "/profile" | "/stories" | "/upcoming-cars" | "/used-cars/[citySlug]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/brand/[brandSlug]": { "brandSlug": string; }
  "/brand/[brandSlug]/[modelSlug]": { "brandSlug": string; "modelSlug": string; }
  "/brand/[brandSlug]/[modelSlug]/photos": { "brandSlug": string; "modelSlug": string; }
  "/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]": { "brandSlug": string; "modelSlug": string; "variantSlug": string; }
  "/brands": {}
  "/car-affordability-calculator": {}
  "/car-loan-emi-calculator": {}
  "/compare-cars": {}
  "/compare/[comparisonSlug]": { "comparisonSlug": string; }
  "/down-payment-calculator": {}
  "/electric-cars": {}
  "/ev-charging-time-calculator": {}
  "/fuel-comparison-calculator": {}
  "/fuel-price": {}
  "/fuel-price/[citySlug]": { "citySlug": string; }
  "/maintenance": {}
  "/mileage-calculator": {}
  "/new-cars": {}
  "/new-cars/[bodyType]": { "bodyType": string; }
  "/news/[categorySlug]": { "categorySlug": string; }
  "/news/[categorySlug]/[articleSlug]": { "categorySlug": string; "articleSlug": string; }
  "/profile": {}
  "/stories": {}
  "/upcoming-cars": {}
  "/used-cars/[citySlug]": { "citySlug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
