// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/brand/[brandSlug]/[modelSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/[brandSlug]/[modelSlug]">> = Specific
  const handler = {} as typeof import("../../app/brand/[brandSlug]/[modelSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brand/[brandSlug]/[modelSlug]/photos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/[brandSlug]/[modelSlug]/photos">> = Specific
  const handler = {} as typeof import("../../app/brand/[brandSlug]/[modelSlug]/photos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]">> = Specific
  const handler = {} as typeof import("../../app/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brand/[brandSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/[brandSlug]">> = Specific
  const handler = {} as typeof import("../../app/brand/[brandSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands">> = Specific
  const handler = {} as typeof import("../../app/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/car-affordability-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/car-affordability-calculator">> = Specific
  const handler = {} as typeof import("../../app/car-affordability-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/car-loan-emi-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/car-loan-emi-calculator">> = Specific
  const handler = {} as typeof import("../../app/car-loan-emi-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare-cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare-cars">> = Specific
  const handler = {} as typeof import("../../app/compare-cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare/[comparisonSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare/[comparisonSlug]">> = Specific
  const handler = {} as typeof import("../../app/compare/[comparisonSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/down-payment-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/down-payment-calculator">> = Specific
  const handler = {} as typeof import("../../app/down-payment-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/electric-cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/electric-cars">> = Specific
  const handler = {} as typeof import("../../app/electric-cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ev-charging-time-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ev-charging-time-calculator">> = Specific
  const handler = {} as typeof import("../../app/ev-charging-time-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fuel-comparison-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel-comparison-calculator">> = Specific
  const handler = {} as typeof import("../../app/fuel-comparison-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fuel-price/[citySlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel-price/[citySlug]">> = Specific
  const handler = {} as typeof import("../../app/fuel-price/[citySlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fuel-price/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel-price">> = Specific
  const handler = {} as typeof import("../../app/fuel-price/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mileage-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mileage-calculator">> = Specific
  const handler = {} as typeof import("../../app/mileage-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-cars/[bodyType]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-cars/[bodyType]">> = Specific
  const handler = {} as typeof import("../../app/new-cars/[bodyType]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-cars">> = Specific
  const handler = {} as typeof import("../../app/new-cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/[categorySlug]/[articleSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[categorySlug]/[articleSlug]">> = Specific
  const handler = {} as typeof import("../../app/news/[categorySlug]/[articleSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/[categorySlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[categorySlug]">> = Specific
  const handler = {} as typeof import("../../app/news/[categorySlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upcoming-cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upcoming-cars">> = Specific
  const handler = {} as typeof import("../../app/upcoming-cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/used-cars/[citySlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/used-cars/[citySlug]">> = Specific
  const handler = {} as typeof import("../../app/used-cars/[citySlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
