var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/stories/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1r3_xr0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0rtl2e5.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xal6c0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qdrf8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_stories_page_actions_1c8vk8g.js")
R.m(12442)
module.exports=R.m(12442).exports
