var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/brand/[brandSlug]/[modelSlug]/page.js")
R.c("server/chunks/ssr/_1byf6ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-wacf3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ypm6fc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ai3sl0.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xal6c0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qdrf8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_brand_[brandSlug]_[modelSlug]_page_actions_1rvsl96.js")
R.m(15817)
module.exports=R.m(15817).exports
