var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/brands/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__17ap1dd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1s4difg.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xal6c0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qdrf8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_brands_page_actions_1zuuafq.js")
R.m(47625)
module.exports=R.m(47625).exports
