var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/brand/[brandSlug]/[modelSlug]/variant/[variantSlug]/page.js")
R.c("server/chunks/ssr/_1byf6ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1h5a2za._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ypm6fc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1zwezsi.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xal6c0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qdrf8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/1jng_app_brand_[brandSlug]_[modelSlug]_variant_[variantSlug]_page_actions_1031-un.js")
R.m(63045)
module.exports=R.m(63045).exports
