// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package store

import (
	"context"
)

const adCampaignPlacement = `-- name: AdCampaignPlacement :one
SELECT id, placement_id FROM ad_campaigns WHERE id = $1
`

type AdCampaignPlacementRow struct {
	ID          int32 `json:"id"`
	PlacementID int32 `json:"placement_id"`
}

// Confirms a campaign exists and is the one that owns the placement the
// caller claims. Impressions and clicks arrive from the browser, so the
// pairing is checked here rather than trusted.
func (q *Queries) AdCampaignPlacement(ctx context.Context, id int32) (AdCampaignPlacementRow, error) {
	row := q.db.QueryRow(ctx, adCampaignPlacement, id)
	var i AdCampaignPlacementRow
	err := row.Scan(&i.ID, &i.PlacementID)
	return i, err
}

const recordAdClick = `-- name: RecordAdClick :exec
INSERT INTO ad_clicks (
  campaign_id, placement_id, impression_id, page_url, referrer_url, device_type, ip_address, session_id, user_agent, clicked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
`

type RecordAdClickParams struct {
	CampaignID   int32   `json:"campaign_id"`
	PlacementID  *int32  `json:"placement_id"`
	ImpressionID *int64  `json:"impression_id"`
	PageUrl      *string `json:"page_url"`
	ReferrerUrl  *string `json:"referrer_url"`
	DeviceType   *string `json:"device_type"`
	IpAddress    *string `json:"ip_address"`
	SessionID    *string `json:"session_id"`
	UserAgent    *string `json:"user_agent"`
}

// impression_id is optional: a click whose impression never reached us
// is still a click, and dropping it would under-count the thing the
// advertiser is paying for.
func (q *Queries) RecordAdClick(ctx context.Context, arg RecordAdClickParams) error {
	_, err := q.db.Exec(ctx, recordAdClick,
		arg.CampaignID,
		arg.PlacementID,
		arg.ImpressionID,
		arg.PageUrl,
		arg.ReferrerUrl,
		arg.DeviceType,
		arg.IpAddress,
		arg.SessionID,
		arg.UserAgent,
	)
	return err
}

const recordAdImpression = `-- name: RecordAdImpression :one
INSERT INTO ad_impressions (
  campaign_id, placement_id, page_url, referrer_url, device_type, ip_address, session_id, user_agent, viewed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
RETURNING id
`

type RecordAdImpressionParams struct {
	CampaignID  int32   `json:"campaign_id"`
	PlacementID *int32  `json:"placement_id"`
	PageUrl     *string `json:"page_url"`
	ReferrerUrl *string `json:"referrer_url"`
	DeviceType  *string `json:"device_type"`
	IpAddress   *string `json:"ip_address"`
	SessionID   *string `json:"session_id"`
	UserAgent   *string `json:"user_agent"`
}

// One row per ad actually rendered. Returns the id so a click arriving
// later can be tied back to the impression that produced it.
func (q *Queries) RecordAdImpression(ctx context.Context, arg RecordAdImpressionParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordAdImpression,
		arg.CampaignID,
		arg.PlacementID,
		arg.PageUrl,
		arg.ReferrerUrl,
		arg.DeviceType,
		arg.IpAddress,
		arg.SessionID,
		arg.UserAgent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const serveAdForPlacement = `-- name: ServeAdForPlacement :one
SELECT c.id,
       c.placement_id,
       c.creative_type,
       c.creative_image_url,
       c.target_url,
       c.script_src,
       c.script_attrs,
       c.name,
       p.dimensions,
       p.slug AS placement_slug
FROM ad_campaigns c
JOIN ad_placements p ON p.id = c.placement_id
WHERE p.slug = $1
  AND p.is_active = true
  AND c.status = 'active'
  AND (c.start_date IS NULL OR c.start_date <= now())
  AND (c.end_date IS NULL OR c.end_date >= now())
ORDER BY c.priority DESC, c.id DESC
LIMIT 1
`

type ServeAdForPlacementRow struct {
	ID               int32   `json:"id"`
	PlacementID      int32   `json:"placement_id"`
	CreativeType     string  `json:"creative_type"`
	CreativeImageUrl *string `json:"creative_image_url"`
	TargetUrl        *string `json:"target_url"`
	ScriptSrc        *string `json:"script_src"`
	ScriptAttrs      []byte  `json:"script_attrs"`
	Name             string  `json:"name"`
	Dimensions       string  `json:"dimensions"`
	PlacementSlug    string  `json:"placement_slug"`
}

// The campaign to show in one placement, right now.
//
// A campaign qualifies when it is active, its placement is active, and
// today falls inside its window — an absent start or end date means
// "already running" and "runs until stopped" respectively, which is how
// the admin panel leaves them when a campaign has no fixed term.
//
// Highest priority wins; ties go to the newest campaign, so replacing a
// creative is a new row rather than an edit to a live one.
func (q *Queries) ServeAdForPlacement(ctx context.Context, slug string) (ServeAdForPlacementRow, error) {
	row := q.db.QueryRow(ctx, serveAdForPlacement, slug)
	var i ServeAdForPlacementRow
	err := row.Scan(
		&i.ID,
		&i.PlacementID,
		&i.CreativeType,
		&i.CreativeImageUrl,
		&i.TargetUrl,
		&i.ScriptSrc,
		&i.ScriptAttrs,
		&i.Name,
		&i.Dimensions,
		&i.PlacementSlug,
	)
	return i, err
}
