// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
)

const recordPageView = `-- name: RecordPageView :exec
INSERT INTO page_view_daily_stats (page_url, view_date, view_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (page_url, view_date)
DO UPDATE SET view_count = page_view_daily_stats.view_count + 1
`

// One row per page per day: a visit increments that day's counter rather
// than inserting a row, so the table grows with distinct pages × days
// instead of with raw traffic.
//
// The day boundary is the server's local calendar day, matching how the
// admin dashboard reads these rows back. CURRENT_DATE in a session set to
// IST is exactly Node's startOfToday(); using UTC would roll "today" back
// to yesterday for any timezone ahead of it.
func (q *Queries) RecordPageView(ctx context.Context, pageUrl string) error {
	_, err := q.db.Exec(ctx, recordPageView, pageUrl)
	return err
}
