// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package store

import (
	"context"
	"time"
)

const countArticlesInCategory = `-- name: CountArticlesInCategory :one
SELECT count(*)
FROM articles a
JOIN article_categories c ON c.id = a.category_id AND c.is_active = true
WHERE c.slug = $1
  AND a.status = 'published' AND a.is_active = true
  AND ($2::text IS NULL OR a.slug <> $2::text)
`

type CountArticlesInCategoryParams struct {
	CategorySlug string  `json:"category_slug"`
	ExcludeSlug  *string `json:"exclude_slug"`
}

func (q *Queries) CountArticlesInCategory(ctx context.Context, arg CountArticlesInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesInCategory, arg.CategorySlug, arg.ExcludeSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArticleCategories = `-- name: ListArticleCategories :many
SELECT c.id, c.name, c.slug
FROM article_categories c
WHERE c.is_active = true
ORDER BY c.name ASC
`

type ListArticleCategoriesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Powers the News nav dropdown.
func (q *Queries) ListArticleCategories(ctx context.Context) ([]ListArticleCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listArticleCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleCategoriesRow{}
	for rows.Next() {
		var i ListArticleCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesInCategory = `-- name: ListArticlesInCategory :many
SELECT a.id, a.title, a.slug, a.excerpt, a.cover_image_url,
       a.read_time_minutes, a.published_at,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
       au.id AS author_id, au.name AS author_name
FROM articles a
JOIN article_categories c ON c.id = a.category_id AND c.is_active = true
JOIN admin_users au ON au.id = a.author_id
WHERE c.slug = $1
  AND a.status = 'published' AND a.is_active = true
  AND ($2::text IS NULL OR a.slug <> $2::text)
ORDER BY a.published_at DESC
LIMIT $4 OFFSET $3
`

type ListArticlesInCategoryParams struct {
	CategorySlug string  `json:"category_slug"`
	ExcludeSlug  *string `json:"exclude_slug"`
	RowOffset    int32   `json:"row_offset"`
	RowLimit     int32   `json:"row_limit"`
}

type ListArticlesInCategoryRow struct {
	ID              int32      `json:"id"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Excerpt         *string    `json:"excerpt"`
	CoverImageUrl   *string    `json:"cover_image_url"`
	ReadTimeMinutes *int32     `json:"read_time_minutes"`
	PublishedAt     *time.Time `json:"published_at"`
	CategoryID      int32      `json:"category_id"`
	CategoryName    string     `json:"category_name"`
	CategorySlug    string     `json:"category_slug"`
	AuthorID        int32      `json:"author_id"`
	AuthorName      string     `json:"author_name"`
}

// Serves both the /news/{category} listing and the "more from this
// category" widget; the widget passes the article it is shown beneath so
// it does not recommend the page you are already on.
func (q *Queries) ListArticlesInCategory(ctx context.Context, arg ListArticlesInCategoryParams) ([]ListArticlesInCategoryRow, error) {
	rows, err := q.db.Query(ctx, listArticlesInCategory,
		arg.CategorySlug,
		arg.ExcludeSlug,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesInCategoryRow{}
	for rows.Next() {
		var i ListArticlesInCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CoverImageUrl,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicArticleBySlug = `-- name: PublicArticleBySlug :one
SELECT a.id, a.title, a.slug, a.excerpt, a.body, a.cover_image_url,
       a.read_time_minutes, a.published_at,
       a.meta_title, a.meta_description, a.meta_keywords, a.og_image_url,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
       au.id AS author_id, au.name AS author_name
FROM articles a
JOIN article_categories c ON c.id = a.category_id AND c.is_active = true
JOIN admin_users au ON au.id = a.author_id
WHERE a.slug = $1 AND c.slug = $2
  AND a.status = 'published' AND a.is_active = true
`

type PublicArticleBySlugParams struct {
	ArticleSlug  string `json:"article_slug"`
	CategorySlug string `json:"category_slug"`
}

type PublicArticleBySlugRow struct {
	ID              int32      `json:"id"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Excerpt         *string    `json:"excerpt"`
	Body            *string    `json:"body"`
	CoverImageUrl   *string    `json:"cover_image_url"`
	ReadTimeMinutes *int32     `json:"read_time_minutes"`
	PublishedAt     *time.Time `json:"published_at"`
	MetaTitle       *string    `json:"meta_title"`
	MetaDescription *string    `json:"meta_description"`
	MetaKeywords    *string    `json:"meta_keywords"`
	OgImageUrl      *string    `json:"og_image_url"`
	CategoryID      int32      `json:"category_id"`
	CategoryName    string     `json:"category_name"`
	CategorySlug    string     `json:"category_slug"`
	AuthorID        int32      `json:"author_id"`
	AuthorName      string     `json:"author_name"`
}

// An article is public only when it is published AND active AND its
// category is active — de-activating a category hides everything under it
// even where the article row still says "published".
func (q *Queries) PublicArticleBySlug(ctx context.Context, arg PublicArticleBySlugParams) (PublicArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, publicArticleBySlug, arg.ArticleSlug, arg.CategorySlug)
	var i PublicArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.CoverImageUrl,
		&i.ReadTimeMinutes,
		&i.PublishedAt,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImageUrl,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.AuthorID,
		&i.AuthorName,
	)
	return i, err
}
