// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cars.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const getCarImagesPage = `-- name: GetCarImagesPage :one
SELECT m.id, m.name, b.name AS brand_name, b.slug AS brand_slug
FROM car_models m
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
WHERE m.slug = $1 AND b.slug = $2
`

type GetCarImagesPageParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
}

type GetCarImagesPageRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	BrandName string `json:"brand_name"`
	BrandSlug string `json:"brand_slug"`
}

func (q *Queries) GetCarImagesPage(ctx context.Context, arg GetCarImagesPageParams) (GetCarImagesPageRow, error) {
	row := q.db.QueryRow(ctx, getCarImagesPage, arg.ModelSlug, arg.BrandSlug)
	var i GetCarImagesPageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BrandName,
		&i.BrandSlug,
	)
	return i, err
}

const getCarModelBySlug = `-- name: GetCarModelBySlug :one
SELECT
    m.id, m.name, m.slug, m.launch_status, m.expected_launch_date,
    m.price_min, m.price_max, m.rating_avg, m.cover_image_url,
    m.variant_count,
    b.id AS brand_id, b.name AS brand_name, b.slug AS brand_slug, b.logo_url AS brand_logo_url,
    bt.id AS body_type_id, bt.name AS body_type_name, bt.slug AS body_type_slug
FROM car_models m
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
LEFT JOIN body_types bt ON bt.id = m.body_type_id
WHERE m.slug = $1 AND b.slug = $2
`

type GetCarModelBySlugParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
}

type GetCarModelBySlugRow struct {
	ID                 int32               `json:"id"`
	Name               string              `json:"name"`
	Slug               string              `json:"slug"`
	LaunchStatus       string              `json:"launch_status"`
	ExpectedLaunchDate *time.Time          `json:"expected_launch_date"`
	PriceMin           decimal.NullDecimal `json:"price_min"`
	PriceMax           decimal.NullDecimal `json:"price_max"`
	RatingAvg          decimal.NullDecimal `json:"rating_avg"`
	CoverImageUrl      *string             `json:"cover_image_url"`
	VariantCount       int32               `json:"variant_count"`
	BrandID            int32               `json:"brand_id"`
	BrandName          string              `json:"brand_name"`
	BrandSlug          string              `json:"brand_slug"`
	BrandLogoUrl       *string             `json:"brand_logo_url"`
	BodyTypeID         *int32              `json:"body_type_id"`
	BodyTypeName       *string             `json:"body_type_name"`
	BodyTypeSlug       *string             `json:"body_type_slug"`
}

func (q *Queries) GetCarModelBySlug(ctx context.Context, arg GetCarModelBySlugParams) (GetCarModelBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCarModelBySlug, arg.ModelSlug, arg.BrandSlug)
	var i GetCarModelBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LaunchStatus,
		&i.ExpectedLaunchDate,
		&i.PriceMin,
		&i.PriceMax,
		&i.RatingAvg,
		&i.CoverImageUrl,
		&i.VariantCount,
		&i.BrandID,
		&i.BrandName,
		&i.BrandSlug,
		&i.BrandLogoUrl,
		&i.BodyTypeID,
		&i.BodyTypeName,
		&i.BodyTypeSlug,
	)
	return i, err
}

const listCarArticles = `-- name: ListCarArticles :many
SELECT
    a.id, a.title, a.slug, a.excerpt, a.cover_image_url,
    a.read_time_minutes, a.published_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    au.id AS author_id, au.name AS author_name
FROM articles a
JOIN article_categories c ON c.id = a.category_id AND c.is_active = true
JOIN admin_users au ON au.id = a.author_id
WHERE a.status = 'published' AND a.is_active = true
  AND EXISTS (
      SELECT 1 FROM article_car_models acm
      JOIN car_models m ON m.id = acm.model_id
      JOIN brands b ON b.id = m.brand_id AND b.is_active = true
      WHERE acm.article_id = a.id AND m.slug = $1 AND b.slug = $2
  )
ORDER BY a.published_at DESC
LIMIT $3
`

type ListCarArticlesParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
	Lim       int32  `json:"lim"`
}

type ListCarArticlesRow struct {
	ID              int32      `json:"id"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Excerpt         *string    `json:"excerpt"`
	CoverImageUrl   *string    `json:"cover_image_url"`
	ReadTimeMinutes *int32     `json:"read_time_minutes"`
	PublishedAt     *time.Time `json:"published_at"`
	CategoryID      int32      `json:"category_id"`
	CategoryName    string     `json:"category_name"`
	CategorySlug    string     `json:"category_slug"`
	AuthorID        int32      `json:"author_id"`
	AuthorName      string     `json:"author_name"`
}

func (q *Queries) ListCarArticles(ctx context.Context, arg ListCarArticlesParams) ([]ListCarArticlesRow, error) {
	rows, err := q.db.Query(ctx, listCarArticles, arg.ModelSlug, arg.BrandSlug, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarArticlesRow{}
	for rows.Next() {
		var i ListCarArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CoverImageUrl,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarColors = `-- name: ListCarColors :many
SELECT id, color_name, image_url, additional_cost
FROM car_colors
WHERE model_id = $1
ORDER BY id ASC
`

type ListCarColorsRow struct {
	ID             int32               `json:"id"`
	ColorName      string              `json:"color_name"`
	ImageUrl       *string             `json:"image_url"`
	AdditionalCost decimal.NullDecimal `json:"additional_cost"`
}

func (q *Queries) ListCarColors(ctx context.Context, modelID int32) ([]ListCarColorsRow, error) {
	rows, err := q.db.Query(ctx, listCarColors, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarColorsRow{}
	for rows.Next() {
		var i ListCarColorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ColorName,
			&i.ImageUrl,
			&i.AdditionalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarFaqs = `-- name: ListCarFaqs :many
SELECT f.id, f.question, f.answer
FROM car_faqs f
JOIN car_models m ON m.id = f.model_id
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
WHERE f.is_active = true AND m.slug = $1 AND b.slug = $2
ORDER BY f.display_order ASC
`

type ListCarFaqsParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
}

type ListCarFaqsRow struct {
	ID       int32  `json:"id"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

func (q *Queries) ListCarFaqs(ctx context.Context, arg ListCarFaqsParams) ([]ListCarFaqsRow, error) {
	rows, err := q.db.Query(ctx, listCarFaqs, arg.ModelSlug, arg.BrandSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarFaqsRow{}
	for rows.Next() {
		var i ListCarFaqsRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarImages = `-- name: ListCarImages :many
SELECT id, image_url, is_primary, angle, color_id
FROM car_images
WHERE model_id = $1
ORDER BY is_primary DESC, id ASC
`

type ListCarImagesRow struct {
	ID        int32   `json:"id"`
	ImageUrl  string  `json:"image_url"`
	IsPrimary bool    `json:"is_primary"`
	Angle     *string `json:"angle"`
	ColorID   *int32  `json:"color_id"`
}

func (q *Queries) ListCarImages(ctx context.Context, modelID int32) ([]ListCarImagesRow, error) {
	rows, err := q.db.Query(ctx, listCarImages, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarImagesRow{}
	for rows.Next() {
		var i ListCarImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.IsPrimary,
			&i.Angle,
			&i.ColorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColorShades = `-- name: ListColorShades :many
SELECT color_id, color_hex, sort_order
FROM car_color_shades
WHERE color_id = ANY($1::int[])
ORDER BY color_id, sort_order ASC
`

type ListColorShadesRow struct {
	ColorID   int32  `json:"color_id"`
	ColorHex  string `json:"color_hex"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListColorShades(ctx context.Context, colorIds []int32) ([]ListColorShadesRow, error) {
	rows, err := q.db.Query(ctx, listColorShades, colorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListColorShadesRow{}
	for rows.Next() {
		var i ListColorShadesRow
		if err := rows.Scan(&i.ColorID, &i.ColorHex, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByBrand = `-- name: ListModelsByBrand :many
SELECT id, name, slug, price_min, price_max
FROM car_models
WHERE brand_id = $1 AND launch_status = 'available' AND variant_count > 0
ORDER BY name ASC
`

type ListModelsByBrandRow struct {
	ID       int32               `json:"id"`
	Name     string              `json:"name"`
	Slug     string              `json:"slug"`
	PriceMin decimal.NullDecimal `json:"price_min"`
	PriceMax decimal.NullDecimal `json:"price_max"`
}

func (q *Queries) ListModelsByBrand(ctx context.Context, brandID int32) ([]ListModelsByBrandRow, error) {
	rows, err := q.db.Query(ctx, listModelsByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsByBrandRow{}
	for rows.Next() {
		var i ListModelsByBrandRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PriceMin,
			&i.PriceMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantFeatures = `-- name: ListVariantFeatures :many
SELECT
    vf.value,
    f.id AS feature_id, f.name AS feature_name,
    fc.id AS category_id, fc.name AS category_name, fc.sort_order
FROM variant_features vf
JOIN features f ON f.id = vf.feature_id
LEFT JOIN feature_categories fc ON fc.id = f.category_id
WHERE vf.variant_id = $1
ORDER BY fc.sort_order ASC NULLS LAST, f.name ASC
`

type ListVariantFeaturesRow struct {
	Value        *string `json:"value"`
	FeatureID    int32   `json:"feature_id"`
	FeatureName  string  `json:"feature_name"`
	CategoryID   *int32  `json:"category_id"`
	CategoryName *string `json:"category_name"`
	SortOrder    *int32  `json:"sort_order"`
}

func (q *Queries) ListVariantFeatures(ctx context.Context, variantID int32) ([]ListVariantFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listVariantFeatures, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantFeaturesRow{}
	for rows.Next() {
		var i ListVariantFeaturesRow
		if err := rows.Scan(
			&i.Value,
			&i.FeatureID,
			&i.FeatureName,
			&i.CategoryID,
			&i.CategoryName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantOptions = `-- name: ListVariantOptions :many
SELECT id, variant_name, price, is_top_seller
FROM car_variants
WHERE model_id = $1
ORDER BY is_top_seller DESC, price ASC
LIMIT $2
`

type ListVariantOptionsParams struct {
	ModelID int32 `json:"model_id"`
	Lim     int32 `json:"lim"`
}

type ListVariantOptionsRow struct {
	ID          int32           `json:"id"`
	VariantName string          `json:"variant_name"`
	Price       decimal.Decimal `json:"price"`
	IsTopSeller bool            `json:"is_top_seller"`
}

func (q *Queries) ListVariantOptions(ctx context.Context, arg ListVariantOptionsParams) ([]ListVariantOptionsRow, error) {
	rows, err := q.db.Query(ctx, listVariantOptions, arg.ModelID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantOptionsRow{}
	for rows.Next() {
		var i ListVariantOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantName,
			&i.Price,
			&i.IsTopSeller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantOptionsBySlug = `-- name: ListVariantOptionsBySlug :many
SELECT v.id, v.variant_name, v.price, v.is_top_seller,
       v.seating_capacity,
       (el.variant_id IS NOT NULL)::boolean AS is_electric,
       el.battery_capacity,
       el.claimed_range,
       ice.cubic_capacity,
       ice.claimed_fe,
       ice.fuel_type AS ice_fuel_type
FROM car_variants v
JOIN car_models m ON m.id = v.model_id
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
LEFT JOIN car_powertrains_electric el ON el.variant_id = v.id AND NOT el.is_deleted
LEFT JOIN car_powertrains_ice ice ON ice.variant_id = v.id AND NOT ice.is_deleted
WHERE m.slug = $1 AND b.slug = $2
ORDER BY v.is_top_seller DESC, v.price ASC
`

type ListVariantOptionsBySlugParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
}

type ListVariantOptionsBySlugRow struct {
	ID              int32               `json:"id"`
	VariantName     string              `json:"variant_name"`
	Price           decimal.Decimal     `json:"price"`
	IsTopSeller     bool                `json:"is_top_seller"`
	SeatingCapacity int32               `json:"seating_capacity"`
	IsElectric      bool                `json:"is_electric"`
	BatteryCapacity decimal.NullDecimal `json:"battery_capacity"`
	ClaimedRange    *int32              `json:"claimed_range"`
	CubicCapacity   *int32              `json:"cubic_capacity"`
	ClaimedFe       decimal.NullDecimal `json:"claimed_fe"`
	IceFuelType     *int32              `json:"ice_fuel_type"`
}

// Carries the one spec that distinguishes trims of the same car, so a
// variant table can show what separates them rather than a column of
// near-identical names: battery and range for an EV, engine and rated
// mileage for anything else.
func (q *Queries) ListVariantOptionsBySlug(ctx context.Context, arg ListVariantOptionsBySlugParams) ([]ListVariantOptionsBySlugRow, error) {
	rows, err := q.db.Query(ctx, listVariantOptionsBySlug, arg.ModelSlug, arg.BrandSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantOptionsBySlugRow{}
	for rows.Next() {
		var i ListVariantOptionsBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantName,
			&i.Price,
			&i.IsTopSeller,
			&i.SeatingCapacity,
			&i.IsElectric,
			&i.BatteryCapacity,
			&i.ClaimedRange,
			&i.CubicCapacity,
			&i.ClaimedFe,
			&i.IceFuelType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelVariantFeatures = `-- name: ModelVariantFeatures :many
SELECT v.id AS variant_id, v.price, f.name AS feature_name, vf.value
FROM car_variants v
JOIN car_models m ON m.id = v.model_id
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
JOIN variant_features vf ON vf.variant_id = v.id
JOIN features f ON f.id = vf.feature_id
WHERE m.slug = $1 AND b.slug = $2
ORDER BY v.price ASC, f.name ASC
`

type ModelVariantFeaturesParams struct {
	ModelSlug string `json:"model_slug"`
	BrandSlug string `json:"brand_slug"`
}

type ModelVariantFeaturesRow struct {
	VariantID   int32           `json:"variant_id"`
	Price       decimal.Decimal `json:"price"`
	FeatureName string          `json:"feature_name"`
	Value       *string         `json:"value"`
}

// Every feature of every trim of one model, in price order. The caller
// diffs adjacent trims to work out what each one adds over the last —
// doing it here would need a self-join per variant.
func (q *Queries) ModelVariantFeatures(ctx context.Context, arg ModelVariantFeaturesParams) ([]ModelVariantFeaturesRow, error) {
	rows, err := q.db.Query(ctx, modelVariantFeatures, arg.ModelSlug, arg.BrandSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelVariantFeaturesRow{}
	for rows.Next() {
		var i ModelVariantFeaturesRow
		if err := rows.Scan(
			&i.VariantID,
			&i.Price,
			&i.FeatureName,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentMileageBenchmark = `-- name: SegmentMileageBenchmark :one
SELECT COALESCE(round(avg(e.claimed_fe), 1), 0)::numeric AS avg_kmpl,
       count(*)::bigint AS sample_size
FROM car_powertrains_ice e
JOIN car_variants v ON v.id = e.variant_id
JOIN car_models m ON m.id = v.model_id
WHERE NOT e.is_deleted
  AND e.claimed_fe IS NOT NULL
  AND m.launch_status = 'available'
  AND m.body_type_id = $1
  AND e.fuel_type = $2
`

type SegmentMileageBenchmarkParams struct {
	BodyTypeID *int32 `json:"body_type_id"`
	FuelType   int32  `json:"fuel_type"`
}

type SegmentMileageBenchmarkRow struct {
	AvgKmpl    decimal.Decimal `json:"avg_kmpl"`
	SampleSize int64           `json:"sample_size"`
}

// Average rated mileage for available cars of the same body type and fuel.
// Derived from our own catalogue rather than a published benchmark, so it
// says what cars like this one claim, not what they achieve. Returns the
// sample size with it so a thin segment can be suppressed rather than
// presented as an average.
// COALESCE keeps the scan off a NULL for a segment with no cars; the
// sample size is what decides whether the average is shown at all.
func (q *Queries) SegmentMileageBenchmark(ctx context.Context, arg SegmentMileageBenchmarkParams) (SegmentMileageBenchmarkRow, error) {
	row := q.db.QueryRow(ctx, segmentMileageBenchmark, arg.BodyTypeID, arg.FuelType)
	var i SegmentMileageBenchmarkRow
	err := row.Scan(&i.AvgKmpl, &i.SampleSize)
	return i, err
}
