// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const compareBrandModels = `-- name: CompareBrandModels :many
SELECT m.id, m.price_min, m.brand_id, m.body_type_id
FROM car_models m
JOIN brands b ON b.id = m.brand_id
WHERE b.slug = $1
  AND m.launch_status = 'available'
  AND EXISTS (SELECT 1 FROM car_variants v WHERE v.model_id = m.id)
ORDER BY m.id ASC
`

type CompareBrandModelsRow struct {
	ID         int32               `json:"id"`
	PriceMin   decimal.NullDecimal `json:"price_min"`
	BrandID    int32               `json:"brand_id"`
	BodyTypeID *int32              `json:"body_type_id"`
}

// One brand's own models, for the brand page's cross-brand rail.
func (q *Queries) CompareBrandModels(ctx context.Context, slug string) ([]CompareBrandModelsRow, error) {
	rows, err := q.db.Query(ctx, compareBrandModels, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareBrandModelsRow{}
	for rows.Next() {
		var i CompareBrandModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceMin,
			&i.BrandID,
			&i.BodyTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareCarOptions = `-- name: CompareCarOptions :many
SELECT m.id, m.name, m.slug, m.cover_image_url, m.price_min,
       b.id AS brand_id, b.name AS brand_name
FROM car_models m
JOIN brands b ON b.id = m.brand_id
WHERE m.launch_status = 'available'
  AND EXISTS (SELECT 1 FROM car_variants v WHERE v.model_id = m.id)
ORDER BY b.name ASC, m.name ASC
`

type CompareCarOptionsRow struct {
	ID            int32               `json:"id"`
	Name          string              `json:"name"`
	Slug          string              `json:"slug"`
	CoverImageUrl *string             `json:"cover_image_url"`
	PriceMin      decimal.NullDecimal `json:"price_min"`
	BrandID       int32               `json:"brand_id"`
	BrandName     string              `json:"brand_name"`
}

// The picker on the compare hub: every model a visitor can put in a slot.
// Ordered by brand then model, which is how the list is read.
func (q *Queries) CompareCarOptions(ctx context.Context) ([]CompareCarOptionsRow, error) {
	rows, err := q.db.Query(ctx, compareCarOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareCarOptionsRow{}
	for rows.Next() {
		var i CompareCarOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CoverImageUrl,
			&i.PriceMin,
			&i.BrandID,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareElectricPowertrains = `-- name: CompareElectricPowertrains :many
SELECT p.id, p.is_default, p.motor_type
FROM car_powertrains_electric p
JOIN car_variants v ON v.id = p.variant_id
JOIN car_models m ON m.id = v.model_id
WHERE m.slug = $1 AND v.id = $2 AND NOT p.is_deleted
ORDER BY p.is_default DESC
`

type CompareElectricPowertrainsParams struct {
	Slug string `json:"slug"`
	ID   int32  `json:"id"`
}

type CompareElectricPowertrainsRow struct {
	ID        int32   `json:"id"`
	IsDefault bool    `json:"is_default"`
	MotorType *string `json:"motor_type"`
}

func (q *Queries) CompareElectricPowertrains(ctx context.Context, arg CompareElectricPowertrainsParams) ([]CompareElectricPowertrainsRow, error) {
	rows, err := q.db.Query(ctx, compareElectricPowertrains, arg.Slug, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareElectricPowertrainsRow{}
	for rows.Next() {
		var i CompareElectricPowertrainsRow
		if err := rows.Scan(&i.ID, &i.IsDefault, &i.MotorType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareIcePowertrains = `-- name: CompareIcePowertrains :many
SELECT p.id, p.is_default, p.fuel_type, p.fuel_type_sub_category
FROM car_powertrains_ice p
JOIN car_variants v ON v.id = p.variant_id
JOIN car_models m ON m.id = v.model_id
WHERE m.slug = $1 AND v.id = $2 AND NOT p.is_deleted
ORDER BY p.is_default DESC
`

type CompareIcePowertrainsParams struct {
	Slug string `json:"slug"`
	ID   int32  `json:"id"`
}

type CompareIcePowertrainsRow struct {
	ID                  int32   `json:"id"`
	IsDefault           bool    `json:"is_default"`
	FuelType            int32   `json:"fuel_type"`
	FuelTypeSubCategory *string `json:"fuel_type_sub_category"`
}

// A trim can carry several powertrain rows — the same trim sold as petrol
// and CNG, or petrol MT and AMT. The default leads.
func (q *Queries) CompareIcePowertrains(ctx context.Context, arg CompareIcePowertrainsParams) ([]CompareIcePowertrainsRow, error) {
	rows, err := q.db.Query(ctx, compareIcePowertrains, arg.Slug, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareIcePowertrainsRow{}
	for rows.Next() {
		var i CompareIcePowertrainsRow
		if err := rows.Scan(
			&i.ID,
			&i.IsDefault,
			&i.FuelType,
			&i.FuelTypeSubCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareModelExists = `-- name: CompareModelExists :one
SELECT id FROM car_models WHERE slug = $1
`

func (q *Queries) CompareModelExists(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, compareModelExists, slug)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const compareModelForRivals = `-- name: CompareModelForRivals :one
SELECT m.id, m.price_min, m.brand_id, m.body_type_id
FROM car_models m
JOIN brands b ON b.id = m.brand_id AND b.is_active = true
WHERE m.slug = $1 AND b.slug = $2
`

type CompareModelForRivalsParams struct {
	Slug   string `json:"slug"`
	Slug_2 string `json:"slug_2"`
}

type CompareModelForRivalsRow struct {
	ID         int32               `json:"id"`
	PriceMin   decimal.NullDecimal `json:"price_min"`
	BrandID    int32               `json:"brand_id"`
	BodyTypeID *int32              `json:"body_type_id"`
}

func (q *Queries) CompareModelForRivals(ctx context.Context, arg CompareModelForRivalsParams) (CompareModelForRivalsRow, error) {
	row := q.db.QueryRow(ctx, compareModelForRivals, arg.Slug, arg.Slug_2)
	var i CompareModelForRivalsRow
	err := row.Scan(
		&i.ID,
		&i.PriceMin,
		&i.BrandID,
		&i.BodyTypeID,
	)
	return i, err
}

const compareOtherBrandModels = `-- name: CompareOtherBrandModels :many
SELECT m.id, m.price_min, m.brand_id, m.body_type_id
FROM car_models m
JOIN brands b ON b.id = m.brand_id
WHERE b.slug <> $1
  AND m.launch_status = 'available'
  AND EXISTS (SELECT 1 FROM car_variants v WHERE v.model_id = m.id)
ORDER BY m.id ASC
`

type CompareOtherBrandModelsRow struct {
	ID         int32               `json:"id"`
	PriceMin   decimal.NullDecimal `json:"price_min"`
	BrandID    int32               `json:"brand_id"`
	BodyTypeID *int32              `json:"body_type_id"`
}

func (q *Queries) CompareOtherBrandModels(ctx context.Context, slug string) ([]CompareOtherBrandModelsRow, error) {
	rows, err := q.db.Query(ctx, compareOtherBrandModels, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareOtherBrandModelsRow{}
	for rows.Next() {
		var i CompareOtherBrandModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceMin,
			&i.BrandID,
			&i.BodyTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comparePairCandidates = `-- name: ComparePairCandidates :many
SELECT m.id, m.price_min, m.brand_id, m.body_type_id
FROM car_models m
JOIN brands b ON b.id = m.brand_id
LEFT JOIN body_types bt ON bt.id = m.body_type_id
WHERE m.launch_status = 'available'
  AND EXISTS (SELECT 1 FROM car_variants v WHERE v.model_id = m.id)
  AND ($1::text IS NULL OR b.slug = $1)
  AND (
        $2::text IS NULL
          AND (bt.slug IS NULL OR bt.slug <> ALL ($3::text[]))
        OR bt.slug = $2
      )
  AND ($4::numeric IS NULL OR m.price_min >= $4)
  AND ($5::numeric IS NULL OR m.price_min <= $5)
  AND (
        $6::int IS NULL
        OR EXISTS (
             SELECT 1 FROM car_variants v
             JOIN car_powertrains_ice ice ON ice.variant_id = v.id AND NOT ice.is_deleted
             WHERE v.model_id = m.id AND ice.fuel_type = $6
           )
      )
  AND (
        NOT $7::boolean
        OR EXISTS (
             SELECT 1 FROM car_variants v
             JOIN car_powertrains_electric el ON el.variant_id = v.id AND NOT el.is_deleted
             WHERE v.model_id = m.id
           )
      )
ORDER BY m.id ASC
`

type ComparePairCandidatesParams struct {
	BrandSlug         *string             `json:"brand_slug"`
	BodyTypeSlug      *string             `json:"body_type_slug"`
	ExcludedBodyTypes []string            `json:"excluded_body_types"`
	MinPrice          decimal.NullDecimal `json:"min_price"`
	MaxPrice          decimal.NullDecimal `json:"max_price"`
	FuelCode          *int32              `json:"fuel_code"`
	ElectricOnly      bool                `json:"electric_only"`
}

type ComparePairCandidatesRow struct {
	ID         int32               `json:"id"`
	PriceMin   decimal.NullDecimal `json:"price_min"`
	BrandID    int32               `json:"brand_id"`
	BodyTypeID *int32              `json:"body_type_id"`
}

// Every model eligible for a comparison pair, with only what the pairing
// needs: price to band by, brand to avoid pairing a marque with itself,
// body type because two cars costing the same are comparable only if they
// are the same kind of vehicle.
//
// Filters are all optional and applied in one pass. NULL body_type_slug
// excludes commercial shapes; naming one asks for them on purpose.
func (q *Queries) ComparePairCandidates(ctx context.Context, arg ComparePairCandidatesParams) ([]ComparePairCandidatesRow, error) {
	rows, err := q.db.Query(ctx, comparePairCandidates,
		arg.BrandSlug,
		arg.BodyTypeSlug,
		arg.ExcludedBodyTypes,
		arg.MinPrice,
		arg.MaxPrice,
		arg.FuelCode,
		arg.ElectricOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparePairCandidatesRow{}
	for rows.Next() {
		var i ComparePairCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceMin,
			&i.BrandID,
			&i.BodyTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comparePairCars = `-- name: ComparePairCars :many
SELECT m.id, m.name, m.slug, m.cover_image_url, m.price_min,
       b.id AS brand_id, b.name AS brand_name
FROM car_models m
JOIN brands b ON b.id = m.brand_id
WHERE m.id = ANY ($1::int[])
`

type ComparePairCarsRow struct {
	ID            int32               `json:"id"`
	Name          string              `json:"name"`
	Slug          string              `json:"slug"`
	CoverImageUrl *string             `json:"cover_image_url"`
	PriceMin      decimal.NullDecimal `json:"price_min"`
	BrandID       int32               `json:"brand_id"`
	BrandName     string              `json:"brand_name"`
}

// The display fields for a set of already-chosen ids.
func (q *Queries) ComparePairCars(ctx context.Context, ids []int32) ([]ComparePairCarsRow, error) {
	rows, err := q.db.Query(ctx, comparePairCars, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparePairCarsRow{}
	for rows.Next() {
		var i ComparePairCarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CoverImageUrl,
			&i.PriceMin,
			&i.BrandID,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareRivalCandidates = `-- name: CompareRivalCandidates :many
SELECT m.id, m.price_min, m.brand_id, m.body_type_id
FROM car_models m
WHERE m.launch_status = 'available'
  AND m.id <> $1
  AND EXISTS (SELECT 1 FROM car_variants v WHERE v.model_id = m.id)
ORDER BY m.id ASC
`

type CompareRivalCandidatesRow struct {
	ID         int32               `json:"id"`
	PriceMin   decimal.NullDecimal `json:"price_min"`
	BrandID    int32               `json:"brand_id"`
	BodyTypeID *int32              `json:"body_type_id"`
}

// Models that could be cross-shopped against one car: everything on sale
// except itself. The tiering (same body, price window, cross-brand) is
// applied in Go, where the rules are readable.
func (q *Queries) CompareRivalCandidates(ctx context.Context, excludeID int32) ([]CompareRivalCandidatesRow, error) {
	rows, err := q.db.Query(ctx, compareRivalCandidates, excludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareRivalCandidatesRow{}
	for rows.Next() {
		var i CompareRivalCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceMin,
			&i.BrandID,
			&i.BodyTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareVariantBelongsToModel = `-- name: CompareVariantBelongsToModel :one
SELECT v.id
FROM car_variants v
JOIN car_models m ON m.id = v.model_id
WHERE v.id = $1 AND m.slug = $2
`

type CompareVariantBelongsToModelParams struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CompareVariantBelongsToModel(ctx context.Context, arg CompareVariantBelongsToModelParams) (int32, error) {
	row := q.db.QueryRow(ctx, compareVariantBelongsToModel, arg.ID, arg.Slug)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const compareVariantOptions = `-- name: CompareVariantOptions :many
SELECT v.id, v.variant_name, v.price
FROM car_variants v
JOIN car_models m ON m.id = v.model_id
WHERE m.slug = $1
ORDER BY v.is_top_seller DESC, v.price ASC
`

type CompareVariantOptionsRow struct {
	ID          int32           `json:"id"`
	VariantName string          `json:"variant_name"`
	Price       decimal.Decimal `json:"price"`
}

// Trims of one model, best-seller first then cheapest — the same order
// the variant table and the model page use.
func (q *Queries) CompareVariantOptions(ctx context.Context, slug string) ([]CompareVariantOptionsRow, error) {
	rows, err := q.db.Query(ctx, compareVariantOptions, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareVariantOptionsRow{}
	for rows.Next() {
		var i CompareVariantOptionsRow
		if err := rows.Scan(&i.ID, &i.VariantName, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
