// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const fuelCityBySlug = `-- name: FuelCityBySlug :one
SELECT c.id, c.name, c.slug, s.id AS state_id, s.name AS state_name
FROM cities c JOIN states s ON s.id = c.state_id
WHERE c.slug = $1 LIMIT 1
`

type FuelCityBySlugRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	StateID   int32  `json:"state_id"`
	StateName string `json:"state_name"`
}

func (q *Queries) FuelCityBySlug(ctx context.Context, slug string) (FuelCityBySlugRow, error) {
	row := q.db.QueryRow(ctx, fuelCityBySlug, slug)
	var i FuelCityBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StateID,
		&i.StateName,
	)
	return i, err
}

const fuelCityInState = `-- name: FuelCityInState :one
SELECT c.id, c.name, c.slug, s.id AS state_id, s.name AS state_name, s.slug AS state_slug
FROM cities c JOIN states s ON s.id = c.state_id
WHERE s.slug = $1 AND c.slug = $2
LIMIT 1
`

type FuelCityInStateParams struct {
	Slug   string `json:"slug"`
	Slug_2 string `json:"slug_2"`
}

type FuelCityInStateRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	StateID   int32  `json:"state_id"`
	StateName string `json:"state_name"`
	StateSlug string `json:"state_slug"`
}

// Slugs are unique per state, not globally, so both halves are needed.
func (q *Queries) FuelCityInState(ctx context.Context, arg FuelCityInStateParams) (FuelCityInStateRow, error) {
	row := q.db.QueryRow(ctx, fuelCityInState, arg.Slug, arg.Slug_2)
	var i FuelCityInStateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StateID,
		&i.StateName,
		&i.StateSlug,
	)
	return i, err
}

const fuelCityIndex = `-- name: FuelCityIndex :many
SELECT c.name AS city_name, c.slug AS city_slug,
       s.name AS state_name, s.slug AS state_slug
FROM cities c
JOIN states s ON s.id = c.state_id
WHERE EXISTS (SELECT 1 FROM fuel_prices f WHERE f.city_id = c.id)
ORDER BY c.name
`

type FuelCityIndexRow struct {
	CityName  string `json:"city_name"`
	CitySlug  string `json:"city_slug"`
	StateName string `json:"state_name"`
	StateSlug string `json:"state_slug"`
}

// Every city we hold a price for, with its state, for the city search.
// Fetched once on first interaction rather than shipped with the page.
func (q *Queries) FuelCityIndex(ctx context.Context) ([]FuelCityIndexRow, error) {
	rows, err := q.db.Query(ctx, fuelCityIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelCityIndexRow{}
	for rows.Next() {
		var i FuelCityIndexRow
		if err := rows.Scan(
			&i.CityName,
			&i.CitySlug,
			&i.StateName,
			&i.StateSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelCityRange = `-- name: FuelCityRange :many
SELECT fuel_type, min(price)::numeric AS low, max(price)::numeric AS high
FROM fuel_prices
WHERE city_id = $1 AND applicable_on >= CURRENT_DATE - 30
GROUP BY fuel_type
`

type FuelCityRangeRow struct {
	FuelType int16           `json:"fuel_type"`
	Low      decimal.Decimal `json:"low"`
	High     decimal.Decimal `json:"high"`
}

// The city's own 30-day low and high, per fuel.
func (q *Queries) FuelCityRange(ctx context.Context, cityID int32) ([]FuelCityRangeRow, error) {
	rows, err := q.db.Query(ctx, fuelCityRange, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelCityRangeRow{}
	for rows.Next() {
		var i FuelCityRangeRow
		if err := rows.Scan(&i.FuelType, &i.Low, &i.High); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelCityStateBySlug = `-- name: FuelCityStateBySlug :one
SELECT c.slug AS city_slug, s.slug AS state_slug
FROM cities c JOIN states s ON s.id = c.state_id
JOIN fuel_prices f ON f.city_id = c.id
WHERE c.slug = $1
GROUP BY c.slug, s.slug
ORDER BY count(f.id) DESC
LIMIT 1
`

type FuelCityStateBySlugRow struct {
	CitySlug  string `json:"city_slug"`
	StateSlug string `json:"state_slug"`
}

// Resolves a bare city slug to its state, for redirecting legacy
// /fuel-price/{city} URLs to the state-scoped path.
func (q *Queries) FuelCityStateBySlug(ctx context.Context, slug string) (FuelCityStateBySlugRow, error) {
	row := q.db.QueryRow(ctx, fuelCityStateBySlug, slug)
	var i FuelCityStateBySlugRow
	err := row.Scan(&i.CitySlug, &i.StateSlug)
	return i, err
}

const fuelPriceBenchmarks = `-- name: FuelPriceBenchmarks :many
WITH latest AS (
    SELECT DISTINCT ON (f.city_id, f.fuel_type)
           f.fuel_type, f.price, c.state_id
    FROM fuel_prices f
    JOIN cities c ON c.id = f.city_id
    WHERE f.applicable_on >= CURRENT_DATE - 7
    ORDER BY f.city_id, f.fuel_type, f.applicable_on DESC
)
SELECT fuel_type,
       round(coalesce(avg(price) FILTER (WHERE state_id = $1), 0), 2)::numeric AS state_avg,
       round(avg(price), 2)::numeric AS national_avg
FROM latest
GROUP BY fuel_type
`

type FuelPriceBenchmarksRow struct {
	FuelType    int16           `json:"fuel_type"`
	StateAvg    decimal.Decimal `json:"state_avg"`
	NationalAvg decimal.Decimal `json:"national_avg"`
}

// What a city's price should be read against: its state's average today
// and India's. Restricted to the last week so a city whose feed stalled
// cannot drag an average down with a month-old number.
func (q *Queries) FuelPriceBenchmarks(ctx context.Context, stateID int32) ([]FuelPriceBenchmarksRow, error) {
	rows, err := q.db.Query(ctx, fuelPriceBenchmarks, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelPriceBenchmarksRow{}
	for rows.Next() {
		var i FuelPriceBenchmarksRow
		if err := rows.Scan(&i.FuelType, &i.StateAvg, &i.NationalAvg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelPriceHistory = `-- name: FuelPriceHistory :many
SELECT f.applicable_on, f.price, f.price_change
FROM fuel_prices f
WHERE f.city_id = $1 AND f.fuel_type = $2
ORDER BY f.applicable_on DESC
LIMIT $3
`

type FuelPriceHistoryParams struct {
	CityID   int32 `json:"city_id"`
	FuelType int16 `json:"fuel_type"`
	Limit    int32 `json:"limit"`
}

type FuelPriceHistoryRow struct {
	ApplicableOn time.Time       `json:"applicable_on"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
}

func (q *Queries) FuelPriceHistory(ctx context.Context, arg FuelPriceHistoryParams) ([]FuelPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, fuelPriceHistory, arg.CityID, arg.FuelType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelPriceHistoryRow{}
	for rows.Next() {
		var i FuelPriceHistoryRow
		if err := rows.Scan(&i.ApplicableOn, &i.Price, &i.PriceChange); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelPricesForCities = `-- name: FuelPricesForCities :many
SELECT DISTINCT ON (c.id, f.fuel_type)
       c.id AS city_id, c.name AS city_name, c.slug AS city_slug,
       s.name AS state_name, s.slug AS state_slug,
       f.fuel_type, f.price, f.price_change, f.applicable_on
FROM unnest($1::text[]) AS want(key)
JOIN states s ON s.slug = split_part(want.key, '/', 1)
JOIN cities c ON c.state_id = s.id AND c.slug = split_part(want.key, '/', 2)
JOIN fuel_prices f ON f.city_id = c.id
ORDER BY c.id, f.fuel_type, f.applicable_on DESC
`

type FuelPricesForCitiesRow struct {
	CityID       int32           `json:"city_id"`
	CityName     string          `json:"city_name"`
	CitySlug     string          `json:"city_slug"`
	StateName    string          `json:"state_name"`
	StateSlug    string          `json:"state_slug"`
	FuelType     int16           `json:"fuel_type"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
	ApplicableOn time.Time       `json:"applicable_on"`
}

// Latest prices for an explicit list of cities, each keyed "state/city".
// Paired rather than a flat slug list because city slugs repeat across
// states, and one key per row because sqlc cannot type two-array unnest.
func (q *Queries) FuelPricesForCities(ctx context.Context, keys []string) ([]FuelPricesForCitiesRow, error) {
	rows, err := q.db.Query(ctx, fuelPricesForCities, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelPricesForCitiesRow{}
	for rows.Next() {
		var i FuelPricesForCitiesRow
		if err := rows.Scan(
			&i.CityID,
			&i.CityName,
			&i.CitySlug,
			&i.StateName,
			&i.StateSlug,
			&i.FuelType,
			&i.Price,
			&i.PriceChange,
			&i.ApplicableOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelStateBySlug = `-- name: FuelStateBySlug :one
SELECT s.id, s.name, s.slug, count(DISTINCT f.city_id) AS city_count
FROM states s
JOIN cities c ON c.state_id = s.id
JOIN fuel_prices f ON f.city_id = c.id
WHERE s.slug = $1
GROUP BY s.id, s.name, s.slug
`

type FuelStateBySlugRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CityCount int64  `json:"city_count"`
}

func (q *Queries) FuelStateBySlug(ctx context.Context, slug string) (FuelStateBySlugRow, error) {
	row := q.db.QueryRow(ctx, fuelStateBySlug, slug)
	var i FuelStateBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CityCount,
	)
	return i, err
}

const fuelStatePriceMatrix = `-- name: FuelStatePriceMatrix :many
WITH latest AS (
    SELECT DISTINCT ON (f.city_id, f.fuel_type)
           f.city_id, f.fuel_type, f.price, c.state_id
    FROM fuel_prices f
    JOIN cities c ON c.id = f.city_id
    WHERE f.applicable_on >= CURRENT_DATE - 7
    ORDER BY f.city_id, f.fuel_type, f.applicable_on DESC
)
SELECT s.id, s.name, s.slug, l.fuel_type,
       round(avg(l.price), 2)::numeric AS avg_price,
       -- Distinct cities in the state, not cities holding this one fuel:
       -- CNG coverage is partial, so a per-fuel count understates it.
       (SELECT count(DISTINCT l2.city_id)
        FROM latest l2 WHERE l2.state_id = l.state_id)::int AS city_count
FROM latest l
JOIN states s ON s.id = l.state_id
GROUP BY s.id, s.name, s.slug, l.fuel_type, l.state_id
ORDER BY s.name
`

type FuelStatePriceMatrixRow struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	FuelType  int16           `json:"fuel_type"`
	AvgPrice  decimal.Decimal `json:"avg_price"`
	CityCount int32           `json:"city_count"`
}

// One row per state per fuel: the average of every city's latest price.
// An average, not a capital-city figure, because the capital is not the
// state and we would be presenting one city's rate as all of it.
func (q *Queries) FuelStatePriceMatrix(ctx context.Context) ([]FuelStatePriceMatrixRow, error) {
	rows, err := q.db.Query(ctx, fuelStatePriceMatrix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelStatePriceMatrixRow{}
	for rows.Next() {
		var i FuelStatePriceMatrixRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FuelType,
			&i.AvgPrice,
			&i.CityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fuelStates = `-- name: FuelStates :many
SELECT s.id, s.name, s.slug, count(DISTINCT f.city_id) AS city_count
FROM states s
JOIN cities c ON c.state_id = s.id
JOIN fuel_prices f ON f.city_id = c.id
GROUP BY s.id, s.name, s.slug
ORDER BY s.name
`

type FuelStatesRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CityCount int64  `json:"city_count"`
}

// Only states we actually hold prices for, so the list never offers a dead end.
func (q *Queries) FuelStates(ctx context.Context) ([]FuelStatesRow, error) {
	rows, err := q.db.Query(ctx, fuelStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelStatesRow{}
	for rows.Next() {
		var i FuelStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestFuelPricesByState = `-- name: LatestFuelPricesByState :many
SELECT DISTINCT ON (c.id)
       c.id AS city_id, c.name AS city_name, c.slug AS city_slug,
       c.is_top_city,
       f.price, f.price_change, f.applicable_on
FROM fuel_prices f
JOIN cities c ON c.id = f.city_id
WHERE c.state_id = $1 AND f.fuel_type = $2
ORDER BY c.id, f.applicable_on DESC
`

type LatestFuelPricesByStateParams struct {
	StateID  int32 `json:"state_id"`
	FuelType int16 `json:"fuel_type"`
}

type LatestFuelPricesByStateRow struct {
	CityID       int32           `json:"city_id"`
	CityName     string          `json:"city_name"`
	CitySlug     string          `json:"city_slug"`
	IsTopCity    bool            `json:"is_top_city"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
	ApplicableOn time.Time       `json:"applicable_on"`
}

// One row per city in a state for a single fuel, newest first.
func (q *Queries) LatestFuelPricesByState(ctx context.Context, arg LatestFuelPricesByStateParams) ([]LatestFuelPricesByStateRow, error) {
	rows, err := q.db.Query(ctx, latestFuelPricesByState, arg.StateID, arg.FuelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestFuelPricesByStateRow{}
	for rows.Next() {
		var i LatestFuelPricesByStateRow
		if err := rows.Scan(
			&i.CityID,
			&i.CityName,
			&i.CitySlug,
			&i.IsTopCity,
			&i.Price,
			&i.PriceChange,
			&i.ApplicableOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestFuelPricesForCity = `-- name: LatestFuelPricesForCity :many
SELECT DISTINCT ON (f.fuel_type)
       f.fuel_type, f.price, f.price_change, f.applicable_on
FROM fuel_prices f
WHERE f.city_id = $1
ORDER BY f.fuel_type, f.applicable_on DESC
`

type LatestFuelPricesForCityRow struct {
	FuelType     int16           `json:"fuel_type"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
	ApplicableOn time.Time       `json:"applicable_on"`
}

// All three fuels for one city at their most recent date. DISTINCT ON gives
// the newest row per fuel without a correlated subquery per type.
func (q *Queries) LatestFuelPricesForCity(ctx context.Context, cityID int32) ([]LatestFuelPricesForCityRow, error) {
	rows, err := q.db.Query(ctx, latestFuelPricesForCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestFuelPricesForCityRow{}
	for rows.Next() {
		var i LatestFuelPricesForCityRow
		if err := rows.Scan(
			&i.FuelType,
			&i.Price,
			&i.PriceChange,
			&i.ApplicableOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metroFuelPrices = `-- name: MetroFuelPrices :many
SELECT DISTINCT ON (c.id, f.fuel_type)
       c.id AS city_id, c.name AS city_name, c.slug AS city_slug,
       s.slug AS state_slug,
       f.fuel_type, f.price, f.price_change, f.applicable_on
FROM fuel_prices f
JOIN cities c ON c.id = f.city_id
JOIN states s ON s.id = c.state_id
WHERE c.slug = ANY($1::text[])
ORDER BY c.id, f.fuel_type, f.applicable_on DESC
`

type MetroFuelPricesRow struct {
	CityID       int32           `json:"city_id"`
	CityName     string          `json:"city_name"`
	CitySlug     string          `json:"city_slug"`
	StateSlug    string          `json:"state_slug"`
	FuelType     int16           `json:"fuel_type"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
	ApplicableOn time.Time       `json:"applicable_on"`
}

// The four metros every fuel page leads with.
func (q *Queries) MetroFuelPrices(ctx context.Context, dollar_1 []string) ([]MetroFuelPricesRow, error) {
	rows, err := q.db.Query(ctx, metroFuelPrices, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetroFuelPricesRow{}
	for rows.Next() {
		var i MetroFuelPricesRow
		if err := rows.Scan(
			&i.CityID,
			&i.CityName,
			&i.CitySlug,
			&i.StateSlug,
			&i.FuelType,
			&i.Price,
			&i.PriceChange,
			&i.ApplicableOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
