// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const incrementBannerClick = `-- name: IncrementBannerClick :one
UPDATE banners SET click_count = click_count + 1
WHERE id = $1
RETURNING id, click_count
`

type IncrementBannerClickRow struct {
	ID         int32 `json:"id"`
	ClickCount int32 `json:"click_count"`
}

func (q *Queries) IncrementBannerClick(ctx context.Context, id int32) (IncrementBannerClickRow, error) {
	row := q.db.QueryRow(ctx, incrementBannerClick, id)
	var i IncrementBannerClickRow
	err := row.Scan(&i.ID, &i.ClickCount)
	return i, err
}

const listActiveBanners = `-- name: ListActiveBanners :many
SELECT id, tag_label, heading, highlight_text, description,
       media_type, image_url, video_url, cta_text, cta_link, display_order
FROM banners
WHERE is_active = true
ORDER BY display_order ASC
`

type ListActiveBannersRow struct {
	ID            int32   `json:"id"`
	TagLabel      string  `json:"tag_label"`
	Heading       string  `json:"heading"`
	HighlightText string  `json:"highlight_text"`
	Description   string  `json:"description"`
	MediaType     int32   `json:"media_type"`
	ImageUrl      *string `json:"image_url"`
	VideoUrl      *string `json:"video_url"`
	CtaText       string  `json:"cta_text"`
	CtaLink       string  `json:"cta_link"`
	DisplayOrder  int32   `json:"display_order"`
}

func (q *Queries) ListActiveBanners(ctx context.Context) ([]ListActiveBannersRow, error) {
	rows, err := q.db.Query(ctx, listActiveBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBannersRow{}
	for rows.Next() {
		var i ListActiveBannersRow
		if err := rows.Scan(
			&i.ID,
			&i.TagLabel,
			&i.Heading,
			&i.HighlightText,
			&i.Description,
			&i.MediaType,
			&i.ImageUrl,
			&i.VideoUrl,
			&i.CtaText,
			&i.CtaLink,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeArticles = `-- name: ListHomeArticles :many
SELECT
    a.id, a.title, a.slug, a.excerpt, a.cover_image_url,
    a.read_time_minutes, a.published_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    au.id AS author_id, au.name AS author_name
FROM articles a
JOIN article_categories c ON c.id = a.category_id
JOIN admin_users au ON au.id = a.author_id
WHERE a.status = 'published' AND a.is_active = true
ORDER BY a.published_at DESC
LIMIT $1
`

type ListHomeArticlesRow struct {
	ID              int32      `json:"id"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Excerpt         *string    `json:"excerpt"`
	CoverImageUrl   *string    `json:"cover_image_url"`
	ReadTimeMinutes *int32     `json:"read_time_minutes"`
	PublishedAt     *time.Time `json:"published_at"`
	CategoryID      int32      `json:"category_id"`
	CategoryName    string     `json:"category_name"`
	CategorySlug    string     `json:"category_slug"`
	AuthorID        int32      `json:"author_id"`
	AuthorName      string     `json:"author_name"`
}

func (q *Queries) ListHomeArticles(ctx context.Context, limit int32) ([]ListHomeArticlesRow, error) {
	rows, err := q.db.Query(ctx, listHomeArticles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeArticlesRow{}
	for rows.Next() {
		var i ListHomeArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CoverImageUrl,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeBodyTypes = `-- name: ListHomeBodyTypes :many
SELECT bt.id, bt.name, bt.slug, bt.icon_url
FROM body_types bt
LEFT JOIN car_models m ON m.body_type_id = bt.id
GROUP BY bt.id, bt.name, bt.slug, bt.icon_url
ORDER BY count(m.id) DESC, bt.name ASC
LIMIT $1
`

type ListHomeBodyTypesRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	IconUrl *string `json:"icon_url"`
}

// Ranked by how many cars actually carry the type, so SUV and Hatchback
// lead and near-empty entries fall off the end of the row rather than
// being surfaced by an accident of alphabet.
func (q *Queries) ListHomeBodyTypes(ctx context.Context, limit int32) ([]ListHomeBodyTypesRow, error) {
	rows, err := q.db.Query(ctx, listHomeBodyTypes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeBodyTypesRow{}
	for rows.Next() {
		var i ListHomeBodyTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeBrands = `-- name: ListHomeBrands :many
SELECT id, name, slug, logo_url
FROM brands
WHERE is_active = true
ORDER BY display_order DESC, name ASC
LIMIT $1
`

type ListHomeBrandsRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	LogoUrl *string `json:"logo_url"`
}

// Ordered by display_order, not name. Alphabetical put Aston Martin,
// Bentley and Bugatti in front of Maruti and Hyundai, which is the wrong
// first impression for an Indian car site. display_order is admin-owned
// so the running order is editorial, not a side effect of spelling.
func (q *Queries) ListHomeBrands(ctx context.Context, limit int32) ([]ListHomeBrandsRow, error) {
	rows, err := q.db.Query(ctx, listHomeBrands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeBrandsRow{}
	for rows.Next() {
		var i ListHomeBrandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeCities = `-- name: ListHomeCities :many
SELECT id, name, slug, logo_url
FROM cities
WHERE is_top_city = true
ORDER BY name ASC
LIMIT $1
`

type ListHomeCitiesRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	LogoUrl *string `json:"logo_url"`
}

func (q *Queries) ListHomeCities(ctx context.Context, limit int32) ([]ListHomeCitiesRow, error) {
	rows, err := q.db.Query(ctx, listHomeCities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeCitiesRow{}
	for rows.Next() {
		var i ListHomeCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeStoryGroups = `-- name: ListHomeStoryGroups :many

SELECT g.id, g.title, g.cover_media_type, g.cover_media_url
FROM story_groups g
WHERE g.is_active = true
  AND EXISTS (SELECT 1 FROM story_items i WHERE i.group_id = g.id AND i.status = 'published')
ORDER BY g.display_order ASC
LIMIT $1
`

type ListHomeStoryGroupsRow struct {
	ID             int32  `json:"id"`
	Title          string `json:"title"`
	CoverMediaType string `json:"cover_media_type"`
	CoverMediaUrl  string `json:"cover_media_url"`
}

// ListHomeStoryGroups and ListStoryItemsForGroups together replace what
// Prisma issued as a nested include. Two round-trips for the whole rail
// regardless of group count, instead of one per group.
func (q *Queries) ListHomeStoryGroups(ctx context.Context, limit int32) ([]ListHomeStoryGroupsRow, error) {
	rows, err := q.db.Query(ctx, listHomeStoryGroups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeStoryGroupsRow{}
	for rows.Next() {
		var i ListHomeStoryGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverMediaType,
			&i.CoverMediaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeTestimonials = `-- name: ListHomeTestimonials :many
SELECT id, customer_name, customer_city, photo_url, rating, quote, created_at
FROM testimonials
WHERE is_active = true AND status = 'approved'
ORDER BY display_order ASC, created_at DESC
LIMIT $1
`

type ListHomeTestimonialsRow struct {
	ID           int32               `json:"id"`
	CustomerName string              `json:"customer_name"`
	CustomerCity *string             `json:"customer_city"`
	PhotoUrl     *string             `json:"photo_url"`
	Rating       decimal.NullDecimal `json:"rating"`
	Quote        string              `json:"quote"`
	CreatedAt    time.Time           `json:"created_at"`
}

func (q *Queries) ListHomeTestimonials(ctx context.Context, limit int32) ([]ListHomeTestimonialsRow, error) {
	rows, err := q.db.Query(ctx, listHomeTestimonials, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeTestimonialsRow{}
	for rows.Next() {
		var i ListHomeTestimonialsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.CustomerCity,
			&i.PhotoUrl,
			&i.Rating,
			&i.Quote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryItemsForGroups = `-- name: ListStoryItemsForGroups :many
SELECT id, group_id, media_type, media_url, description, link
FROM story_items
WHERE group_id = ANY($1::int[]) AND status = 'published'
ORDER BY group_id, display_order ASC
`

type ListStoryItemsForGroupsRow struct {
	ID          int32   `json:"id"`
	GroupID     int32   `json:"group_id"`
	MediaType   string  `json:"media_type"`
	MediaUrl    string  `json:"media_url"`
	Description *string `json:"description"`
	Link        *string `json:"link"`
}

func (q *Queries) ListStoryItemsForGroups(ctx context.Context, groupIds []int32) ([]ListStoryItemsForGroupsRow, error) {
	rows, err := q.db.Query(ctx, listStoryItemsForGroups, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoryItemsForGroupsRow{}
	for rows.Next() {
		var i ListStoryItemsForGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.MediaType,
			&i.MediaUrl,
			&i.Description,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitTestimonial = `-- name: SubmitTestimonial :one
INSERT INTO testimonials (customer_name, customer_city, rating, quote,
                          status, is_active, display_order, created_at)
VALUES ($1, $2, $3, $4, 'pending', true, 0, NOW())
RETURNING id, status
`

type SubmitTestimonialParams struct {
	CustomerName string              `json:"customer_name"`
	CustomerCity *string             `json:"customer_city"`
	Rating       decimal.NullDecimal `json:"rating"`
	Quote        string              `json:"quote"`
}

type SubmitTestimonialRow struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SubmitTestimonial(ctx context.Context, arg SubmitTestimonialParams) (SubmitTestimonialRow, error) {
	row := q.db.QueryRow(ctx, submitTestimonial,
		arg.CustomerName,
		arg.CustomerCity,
		arg.Rating,
		arg.Quote,
	)
	var i SubmitTestimonialRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
