// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const findCityByName = `-- name: FindCityByName :one
SELECT c.id, c.name, c.slug, s.slug AS state_slug
FROM cities c JOIN states s ON s.id = c.state_id
WHERE LOWER(c.name) = LOWER($1)
   OR LOWER($1) LIKE LOWER(c.name) || ' %'
ORDER BY (LOWER(c.name) = LOWER($1)) DESC, length(c.name) DESC
LIMIT 1
`

type FindCityByNameRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	StateSlug string `json:"state_slug"`
}

func (q *Queries) FindCityByName(ctx context.Context, name string) (FindCityByNameRow, error) {
	row := q.db.QueryRow(ctx, findCityByName, name)
	var i FindCityByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StateSlug,
	)
	return i, err
}

const getBodyTypeBySlug = `-- name: GetBodyTypeBySlug :one
SELECT id, name, slug, icon_url, description
FROM body_types
WHERE slug = $1
`

type GetBodyTypeBySlugRow struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	IconUrl     *string `json:"icon_url"`
	Description *string `json:"description"`
}

func (q *Queries) GetBodyTypeBySlug(ctx context.Context, slug string) (GetBodyTypeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBodyTypeBySlug, slug)
	var i GetBodyTypeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IconUrl,
		&i.Description,
	)
	return i, err
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, name, slug, logo_url
FROM brands
WHERE slug = $1 AND is_active = true
`

type GetBrandBySlugRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	LogoUrl *string `json:"logo_url"`
}

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (GetBrandBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i GetBrandBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
	)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT maintenance_mode, maintenance_message, support_email, contact_email,
       contact_number, whatsapp_number, address,
       facebook_url, instagram_url, twitter_url, youtube_url, linkedin_url
FROM site_settings
ORDER BY id ASC
LIMIT 1
`

type GetSiteSettingsRow struct {
	MaintenanceMode    bool    `json:"maintenance_mode"`
	MaintenanceMessage *string `json:"maintenance_message"`
	SupportEmail       *string `json:"support_email"`
	ContactEmail       *string `json:"contact_email"`
	ContactNumber      *string `json:"contact_number"`
	WhatsappNumber     *string `json:"whatsapp_number"`
	Address            *string `json:"address"`
	FacebookUrl        *string `json:"facebook_url"`
	InstagramUrl       *string `json:"instagram_url"`
	TwitterUrl         *string `json:"twitter_url"`
	YoutubeUrl         *string `json:"youtube_url"`
	LinkedinUrl        *string `json:"linkedin_url"`
}

func (q *Queries) GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i GetSiteSettingsRow
	err := row.Scan(
		&i.MaintenanceMode,
		&i.MaintenanceMessage,
		&i.SupportEmail,
		&i.ContactEmail,
		&i.ContactNumber,
		&i.WhatsappNumber,
		&i.Address,
		&i.FacebookUrl,
		&i.InstagramUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.LinkedinUrl,
	)
	return i, err
}

const insertSearchLog = `-- name: InsertSearchLog :exec
INSERT INTO search_logs (search_query, results_count, page_url, device_type,
                         ip_address, session_id, user_agent, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, NOW())
`

type InsertSearchLogParams struct {
	SearchQuery  *string `json:"search_query"`
	ResultsCount *int32  `json:"results_count"`
	PageUrl      *string `json:"page_url"`
	DeviceType   *string `json:"device_type"`
	IpAddress    *string `json:"ip_address"`
	SessionID    *string `json:"session_id"`
	UserAgent    *string `json:"user_agent"`
}

// Search logging is best-effort: a failure here must never break the
// response the user is waiting on, so the caller ignores its error.
func (q *Queries) InsertSearchLog(ctx context.Context, arg InsertSearchLogParams) error {
	_, err := q.db.Exec(ctx, insertSearchLog,
		arg.SearchQuery,
		arg.ResultsCount,
		arg.PageUrl,
		arg.DeviceType,
		arg.IpAddress,
		arg.SessionID,
		arg.UserAgent,
	)
	return err
}

const listBodyTypesWithCounts = `-- name: ListBodyTypesWithCounts :many
SELECT bt.id, bt.name, bt.slug, bt.icon_url, COUNT(m.id) AS count
FROM body_types bt
LEFT JOIN car_models m
       ON m.body_type_id = bt.id
      AND m.launch_status = 'available'
      AND m.variant_count > 0
GROUP BY bt.id, bt.name, bt.slug, bt.icon_url
HAVING COUNT(m.id) > 0
ORDER BY bt.name ASC
`

type ListBodyTypesWithCountsRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	IconUrl *string `json:"icon_url"`
	Count   int64   `json:"count"`
}

// A body type nobody can buy a car in is a filter that returns nothing.
// Five of these existed because "Diesel Engines", "Hybrids", "Luxury",
// "Luxury Vehicles" and "Wagons" were never body types to begin with.
func (q *Queries) ListBodyTypesWithCounts(ctx context.Context) ([]ListBodyTypesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listBodyTypesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBodyTypesWithCountsRow{}
	for rows.Next() {
		var i ListBodyTypesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IconUrl,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, slug, logo_url
FROM brands
WHERE is_active = true
ORDER BY name ASC
`

type ListBrandsRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	LogoUrl *string `json:"logo_url"`
}

func (q *Queries) ListBrands(ctx context.Context) ([]ListBrandsRow, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrandsRow{}
	for rows.Next() {
		var i ListBrandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrandsWithCounts = `-- name: ListBrandsWithCounts :many
SELECT b.id, b.name, b.slug, b.logo_url, COUNT(m.id) AS count
FROM brands b
LEFT JOIN car_models m
       ON m.brand_id = b.id
      AND m.launch_status = 'available'
      AND m.variant_count > 0
WHERE b.is_active = true
GROUP BY b.id, b.name, b.slug, b.logo_url
ORDER BY b.name ASC
`

type ListBrandsWithCountsRow struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
	LogoUrl *string `json:"logo_url"`
	Count   int64   `json:"count"`
}

// ListBrandsWithCounts replaces a groupBy plus a separate findMany that
// the Node service then stitched together in JavaScript. One grouped
// LEFT JOIN keeps zero-count brands in the result, which the caller uses
// to grey them out rather than link to an empty listing.
func (q *Queries) ListBrandsWithCounts(ctx context.Context) ([]ListBrandsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listBrandsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrandsWithCountsRow{}
	for rows.Next() {
		var i ListBrandsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitiesForSelector = `-- name: ListCitiesForSelector :many

SELECT c.id, c.name, c.slug, c.is_top_city, s.slug AS state_slug
FROM cities c JOIN states s ON s.id = c.state_id
ORDER BY c.is_top_city DESC, c.name ASC
`

type ListCitiesForSelectorRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	IsTopCity bool   `json:"is_top_city"`
	StateSlug string `json:"state_slug"`
}

// City slugs are only unique within a state, so every city we hand the
// frontend carries its state slug — that pair is what addresses a city.
func (q *Queries) ListCitiesForSelector(ctx context.Context) ([]ListCitiesForSelectorRow, error) {
	rows, err := q.db.Query(ctx, listCitiesForSelector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesForSelectorRow{}
	for rows.Next() {
		var i ListCitiesForSelectorRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsTopCity,
			&i.StateSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityOptions = `-- name: ListCityOptions :many
SELECT id, name, state_id
FROM cities
ORDER BY name ASC
`

type ListCityOptionsRow struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	StateID int32  `json:"state_id"`
}

func (q *Queries) ListCityOptions(ctx context.Context) ([]ListCityOptionsRow, error) {
	rows, err := q.db.Query(ctx, listCityOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCityOptionsRow{}
	for rows.Next() {
		var i ListCityOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StateID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLenderOptions = `-- name: ListLenderOptions :many
SELECT id, name, logo_url, min_interest_rate, max_interest_rate,
       max_loan_amount, max_tenure_years
FROM lenders
WHERE is_active = true
ORDER BY name ASC
`

type ListLenderOptionsRow struct {
	ID              int32               `json:"id"`
	Name            string              `json:"name"`
	LogoUrl         *string             `json:"logo_url"`
	MinInterestRate decimal.NullDecimal `json:"min_interest_rate"`
	MaxInterestRate decimal.NullDecimal `json:"max_interest_rate"`
	MaxLoanAmount   decimal.NullDecimal `json:"max_loan_amount"`
	MaxTenureYears  *int32              `json:"max_tenure_years"`
}

func (q *Queries) ListLenderOptions(ctx context.Context) ([]ListLenderOptionsRow, error) {
	rows, err := q.db.Query(ctx, listLenderOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLenderOptionsRow{}
	for rows.Next() {
		var i ListLenderOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoUrl,
			&i.MinInterestRate,
			&i.MaxInterestRate,
			&i.MaxLoanAmount,
			&i.MaxTenureYears,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellCarCityOptions = `-- name: ListSellCarCityOptions :many
SELECT id, name, state_id
FROM cities
WHERE is_sell_car_enabled = true
ORDER BY name ASC
`

type ListSellCarCityOptionsRow struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	StateID int32  `json:"state_id"`
}

// Cities where we actually run a buy/scrap service. Filtered in SQL so
// the response carries only rows the form can offer, rather than making
// the browser discard 788 of 799.
func (q *Queries) ListSellCarCityOptions(ctx context.Context) ([]ListSellCarCityOptionsRow, error) {
	rows, err := q.db.Query(ctx, listSellCarCityOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSellCarCityOptionsRow{}
	for rows.Next() {
		var i ListSellCarCityOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StateID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateOptions = `-- name: ListStateOptions :many
SELECT id, name
FROM states
ORDER BY name ASC
`

type ListStateOptionsRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListStateOptions(ctx context.Context) ([]ListStateOptionsRow, error) {
	rows, err := q.db.Query(ctx, listStateOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStateOptionsRow{}
	for rows.Next() {
		var i ListStateOptionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCars = `-- name: SearchCars :many
SELECT m.id, m.name, m.slug, m.cover_image_url, m.price_min,
       b.name AS brand_name, b.slug AS brand_slug
FROM car_models m
JOIN brands b ON b.id = m.brand_id
WHERE NOT (m.launch_status = 'available' AND m.variant_count = 0)
  AND (m.name ILIKE '%' || $1 || '%' OR b.name ILIKE '%' || $1 || '%')
ORDER BY m.rating_avg DESC, m.name ASC
LIMIT $2
`

type SearchCarsParams struct {
	Q   *string `json:"q"`
	Lim int32   `json:"lim"`
}

type SearchCarsRow struct {
	ID            int32               `json:"id"`
	Name          string              `json:"name"`
	Slug          string              `json:"slug"`
	CoverImageUrl *string             `json:"cover_image_url"`
	PriceMin      decimal.NullDecimal `json:"price_min"`
	BrandName     string              `json:"brand_name"`
	BrandSlug     string              `json:"brand_slug"`
}

// SearchCars powers the header search bar, matching on model OR brand
// name. ILIKE with a leading wildcard cannot use a btree index; see the
// pg_trgm note in README.md for the index this wants once the catalogue
// grows enough for it to matter.
//
// The launch_status predicate is deliberately "not (available with no
// variants)" rather than "available with variants": an upcoming model has
// no variants by design but still has a reachable detail page, so
// excluding it here would hide a live page from search.
func (q *Queries) SearchCars(ctx context.Context, arg SearchCarsParams) ([]SearchCarsRow, error) {
	rows, err := q.db.Query(ctx, searchCars, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCarsRow{}
	for rows.Next() {
		var i SearchCarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CoverImageUrl,
			&i.PriceMin,
			&i.BrandName,
			&i.BrandSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
