// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AdCampaign struct {
	ID               int32      `json:"id"`
	PlacementID      int32      `json:"placement_id"`
	AdvertiserID     *int32     `json:"advertiser_id"`
	Name             string     `json:"name"`
	CreativeImageUrl string     `json:"creative_image_url"`
	TargetUrl        string     `json:"target_url"`
	StartDate        *time.Time `json:"start_date"`
	EndDate          *time.Time `json:"end_date"`
	Status           string     `json:"status"`
	CreatedAt        time.Time  `json:"created_at"`
	CreatedBy        *int32     `json:"created_by"`
	UpdatedAt        time.Time  `json:"updated_at"`
	UpdatedBy        *int32     `json:"updated_by"`
	Priority         int32      `json:"priority"`
}

type AdClick struct {
	ID           int64     `json:"id"`
	CampaignID   int32     `json:"campaign_id"`
	UserID       *int32    `json:"user_id"`
	PageUrl      *string   `json:"page_url"`
	DeviceType   *string   `json:"device_type"`
	IpAddress    *string   `json:"ip_address"`
	ClickedAt    time.Time `json:"clicked_at"`
	ImpressionID *int64    `json:"impression_id"`
	PlacementID  *int32    `json:"placement_id"`
	ReferrerUrl  *string   `json:"referrer_url"`
	SessionID    *string   `json:"session_id"`
	UserAgent    *string   `json:"user_agent"`
}

type AdImpression struct {
	ID          int64     `json:"id"`
	CampaignID  int32     `json:"campaign_id"`
	UserID      *int32    `json:"user_id"`
	PageUrl     *string   `json:"page_url"`
	DeviceType  *string   `json:"device_type"`
	IpAddress   *string   `json:"ip_address"`
	ViewedAt    time.Time `json:"viewed_at"`
	PlacementID *int32    `json:"placement_id"`
	ReferrerUrl *string   `json:"referrer_url"`
	SessionID   *string   `json:"session_id"`
	UserAgent   *string   `json:"user_agent"`
}

type AdPlacement struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	Dimensions string    `json:"dimensions"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	CreatedBy  *int32    `json:"created_by"`
	UpdatedAt  time.Time `json:"updated_at"`
	UpdatedBy  *int32    `json:"updated_by"`
	PageType   int32     `json:"page_type"`
	AdType     int32     `json:"ad_type"`
}

type AdminLog struct {
	ID          int64     `json:"id"`
	AdminID     int32     `json:"admin_id"`
	Description *string   `json:"description"`
	IpAddress   *string   `json:"ip_address"`
	CreatedAt   time.Time `json:"created_at"`
}

type AdminOtpVerification struct {
	ID         int32      `json:"id"`
	AdminID    int32      `json:"admin_id"`
	Mobile     string     `json:"mobile"`
	OtpCode    string     `json:"otp_code"`
	Purpose    string     `json:"purpose"`
	IpAddress  *string    `json:"ip_address"`
	ExpiresAt  time.Time  `json:"expires_at"`
	VerifiedAt *time.Time `json:"verified_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type AdminUser struct {
	ID                  int32      `json:"id"`
	Name                string     `json:"name"`
	Email               string     `json:"email"`
	Mobile              string     `json:"mobile"`
	PasswordHash        *string    `json:"password_hash"`
	RoleID              int32      `json:"role_id"`
	Status              string     `json:"status"`
	AccessStartDate     *time.Time `json:"access_start_date"`
	AccessEndDate       *time.Time `json:"access_end_date"`
	LastLoginAt         *time.Time `json:"last_login_at"`
	LastLoginIp         *string    `json:"last_login_ip"`
	FailedLoginAttempts int32      `json:"failed_login_attempts"`
	IsLocked            bool       `json:"is_locked"`
	LockType            *string    `json:"lock_type"`
	LockedBy            *int32     `json:"locked_by"`
	LockedAt            *time.Time `json:"locked_at"`
	LockedReason        *string    `json:"locked_reason"`
	UnlockedBy          *int32     `json:"unlocked_by"`
	UnlockedAt          *time.Time `json:"unlocked_at"`
	CreatedBy           *int32     `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
}

type Advertiser struct {
	ID            int32     `json:"id"`
	Name          string    `json:"name"`
	ContactName   string    `json:"contact_name"`
	ContactMobile string    `json:"contact_mobile"`
	ContactEmail  string    `json:"contact_email"`
	CreatedAt     time.Time `json:"created_at"`
	CreatedBy     *int32    `json:"created_by"`
	IsActive      bool      `json:"is_active"`
	UpdatedAt     time.Time `json:"updated_at"`
	UpdatedBy     *int32    `json:"updated_by"`
}

type AiArticle struct {
	ID                 int32      `json:"id"`
	CategoryID         int32      `json:"category_id"`
	BrandID            int32      `json:"brand_id"`
	ModelID            *int32     `json:"model_id"`
	Title              string     `json:"title"`
	Slug               string     `json:"slug"`
	Excerpt            string     `json:"excerpt"`
	Body               string     `json:"body"`
	CoverImageUrl      string     `json:"cover_image_url"`
	MetaTitle          string     `json:"meta_title"`
	MetaDescription    string     `json:"meta_description"`
	MetaKeywords       string     `json:"meta_keywords"`
	Status             int32      `json:"status"`
	AiProvider         int32      `json:"ai_provider"`
	AiModel            string     `json:"ai_model"`
	PublishedArticleID *int32     `json:"published_article_id"`
	ReviewedBy         *int32     `json:"reviewed_by"`
	ReviewedAt         *time.Time `json:"reviewed_at"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
	SourceImagePoolID  int32      `json:"source_image_pool_id"`
}

type AiAutomationRule struct {
	ID               int32      `json:"id"`
	FeatureKey       int32      `json:"feature_key"`
	Enabled          bool       `json:"enabled"`
	FrequencyMinutes int32      `json:"frequency_minutes"`
	CountPerRun      int32      `json:"count_per_run"`
	AutoDelete       bool       `json:"auto_delete"`
	KeepLatest       *int32     `json:"keep_latest"`
	NextRunAt        *time.Time `json:"next_run_at"`
	LastRunAt        *time.Time `json:"last_run_at"`
	CreatedBy        *int32     `json:"created_by"`
	UpdatedBy        *int32     `json:"updated_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
	AutoPublish      bool       `json:"auto_publish"`
	DeleteStrategy   string     `json:"delete_strategy"`
	Language         string     `json:"language"`
	MaxTotal         *int32     `json:"max_total"`
}

type AiFaq struct {
	ID             int32      `json:"id"`
	ModelID        int32      `json:"model_id"`
	Question       string     `json:"question"`
	Answer         string     `json:"answer"`
	Status         int32      `json:"status"`
	AiProvider     int32      `json:"ai_provider"`
	AiModel        string     `json:"ai_model"`
	PublishedFaqID *int32     `json:"published_faq_id"`
	ReviewedBy     *int32     `json:"reviewed_by"`
	ReviewedAt     *time.Time `json:"reviewed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

type AiImagePool struct {
	ID               int32      `json:"id"`
	FeatureKey       int32      `json:"feature_key"`
	ImageUrl         string     `json:"image_url"`
	OriginalFilename *string    `json:"original_filename"`
	IsUsed           bool       `json:"is_used"`
	UsedForID        *int32     `json:"used_for_id"`
	UsedAt           *time.Time `json:"used_at"`
	UploadedBy       *int32     `json:"uploaded_by"`
	CreatedAt        time.Time  `json:"created_at"`
}

type AiLog struct {
	ID         int64     `json:"id"`
	FeatureKey int32     `json:"feature_key"`
	Action     string    `json:"action"`
	Status     int32     `json:"status"`
	Message    string    `json:"message"`
	Meta       []byte    `json:"meta"`
	DurationMs *int32    `json:"duration_ms"`
	CreatedAt  time.Time `json:"created_at"`
}

type AiSetting struct {
	ID        int32      `json:"id"`
	Provider  int32      `json:"provider"`
	BaseUrl   *string    `json:"base_url"`
	ApiKey    *string    `json:"api_key"`
	Model     string     `json:"model"`
	CreatedBy int32      `json:"created_by"`
	UpdatedBy int32      `json:"updated_by"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type AiStoryItem struct {
	ID                   int32      `json:"id"`
	GroupID              int32      `json:"group_id"`
	SourceImagePoolID    int32      `json:"source_image_pool_id"`
	MediaType            string     `json:"media_type"`
	MediaUrl             string     `json:"media_url"`
	Description          string     `json:"description"`
	Link                 *string    `json:"link"`
	Status               int32      `json:"status"`
	AiProvider           int32      `json:"ai_provider"`
	AiModel              string     `json:"ai_model"`
	PublishedStoryItemID *int32     `json:"published_story_item_id"`
	ReviewedBy           *int32     `json:"reviewed_by"`
	ReviewedAt           *time.Time `json:"reviewed_at"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            *time.Time `json:"updated_at"`
}

type Article struct {
	ID              int32      `json:"id"`
	CategoryID      int32      `json:"category_id"`
	AuthorID        int32      `json:"author_id"`
	CreatedBy       *int32     `json:"created_by"`
	UpdatedBy       *int32     `json:"updated_by"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Excerpt         *string    `json:"excerpt"`
	Body            *string    `json:"body"`
	CoverImageUrl   *string    `json:"cover_image_url"`
	ReadTimeMinutes *int32     `json:"read_time_minutes"`
	Status          string     `json:"status"`
	IsActive        bool       `json:"is_active"`
	ScheduledAt     *time.Time `json:"scheduled_at"`
	PublishedAt     *time.Time `json:"published_at"`
	ViewCount       int32      `json:"view_count"`
	MetaTitle       *string    `json:"meta_title"`
	MetaDescription *string    `json:"meta_description"`
	MetaKeywords    *string    `json:"meta_keywords"`
	OgImageUrl      *string    `json:"og_image_url"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type ArticleBrand struct {
	ID        int32 `json:"id"`
	ArticleID int32 `json:"article_id"`
	BrandID   int32 `json:"brand_id"`
}

type ArticleCarModel struct {
	ID        int32 `json:"id"`
	ArticleID int32 `json:"article_id"`
	ModelID   int32 `json:"model_id"`
}

type ArticleCategory struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	IsActive  bool      `json:"is_active"`
	CreatedBy *int32    `json:"created_by"`
	UpdatedBy *int32    `json:"updated_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArticleComment struct {
	ID              int32     `json:"id"`
	ArticleID       int32     `json:"article_id"`
	UserID          int32     `json:"user_id"`
	ParentCommentID *int32    `json:"parent_comment_id"`
	Body            string    `json:"body"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
}

type AttributeOption struct {
	ID       int32  `json:"id"`
	Category string `json:"category"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
}

type Banner struct {
	ID            int32      `json:"id"`
	Name          string     `json:"name"`
	TagLabel      string     `json:"tag_label"`
	Heading       string     `json:"heading"`
	HighlightText string     `json:"highlight_text"`
	Description   string     `json:"description"`
	MediaType     int32      `json:"media_type"`
	ImageUrl      *string    `json:"image_url"`
	VideoUrl      *string    `json:"video_url"`
	CtaText       string     `json:"cta_text"`
	CtaLink       string     `json:"cta_link"`
	DisplayOrder  int32      `json:"display_order"`
	IsActive      bool       `json:"is_active"`
	ClickCount    int32      `json:"click_count"`
	CreatedBy     int32      `json:"created_by"`
	UpdatedBy     *int32     `json:"updated_by"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type BodyType struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	IconUrl     *string   `json:"icon_url"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Brand struct {
	ID              int32     `json:"id"`
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	LogoUrl         *string   `json:"logo_url"`
	CountryOriginID *int32    `json:"country_origin_id"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
}

type BuyNewCarLead struct {
	ID           int32     `json:"id"`
	UserID       *int32    `json:"user_id"`
	Name         *string   `json:"name"`
	Mobile       string    `json:"mobile"`
	BrandID      *int32    `json:"brand_id"`
	ModelID      *int32    `json:"model_id"`
	CityID       *int32    `json:"city_id"`
	InterestType *string   `json:"interest_type"`
	Status       string    `json:"status"`
	LeadChannel  *string   `json:"lead_channel"`
	UtmSource    *string   `json:"utm_source"`
	UtmMedium    *string   `json:"utm_medium"`
	UtmCampaign  *string   `json:"utm_campaign"`
	LandingPage  *string   `json:"landing_page"`
	DeviceType   *string   `json:"device_type"`
	IpAddress    *string   `json:"ip_address"`
	CreatedAt    time.Time `json:"created_at"`
	Email        *string   `json:"email"`
	UpdatedAt    time.Time `json:"updated_at"`
	VariantID    *int32    `json:"variant_id"`
}

type BuyUsedCarLead struct {
	ID          int32     `json:"id"`
	UserID      *int32    `json:"user_id"`
	Name        *string   `json:"name"`
	Mobile      string    `json:"mobile"`
	BrandID     *int32    `json:"brand_id"`
	ModelID     *int32    `json:"model_id"`
	ListingID   *int32    `json:"listing_id"`
	Status      string    `json:"status"`
	LeadChannel *string   `json:"lead_channel"`
	UtmSource   *string   `json:"utm_source"`
	UtmMedium   *string   `json:"utm_medium"`
	UtmCampaign *string   `json:"utm_campaign"`
	LandingPage *string   `json:"landing_page"`
	DeviceType  *string   `json:"device_type"`
	IpAddress   *string   `json:"ip_address"`
	CreatedAt   time.Time `json:"created_at"`
}

type CarColor struct {
	ID             int32               `json:"id"`
	ModelID        int32               `json:"model_id"`
	ColorName      string              `json:"color_name"`
	ImageUrl       *string             `json:"image_url"`
	AdditionalCost decimal.NullDecimal `json:"additional_cost"`
}

type CarColorShade struct {
	ID        int32  `json:"id"`
	ColorID   int32  `json:"color_id"`
	ColorHex  string `json:"color_hex"`
	SortOrder int32  `json:"sort_order"`
}

type CarFaq struct {
	ID           int32     `json:"id"`
	ModelID      int32     `json:"model_id"`
	Question     string    `json:"question"`
	Answer       string    `json:"answer"`
	DisplayOrder int32     `json:"display_order"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	ViewCount    int32     `json:"view_count"`
}

type CarImage struct {
	ID        int32   `json:"id"`
	ModelID   int32   `json:"model_id"`
	ColorID   *int32  `json:"color_id"`
	ImageUrl  string  `json:"image_url"`
	IsPrimary bool    `json:"is_primary"`
	Angle     *string `json:"angle"`
}

type CarModel struct {
	ID                 int32               `json:"id"`
	BrandID            int32               `json:"brand_id"`
	Name               string              `json:"name"`
	Slug               string              `json:"slug"`
	BodyTypeID         *int32              `json:"body_type_id"`
	LaunchStatus       string              `json:"launch_status"`
	ExpectedLaunchDate *time.Time          `json:"expected_launch_date"`
	PriceMin           decimal.NullDecimal `json:"price_min"`
	PriceMax           decimal.NullDecimal `json:"price_max"`
	RatingAvg          decimal.NullDecimal `json:"rating_avg"`
	CoverImageUrl      *string             `json:"cover_image_url"`
	CreatedAt          time.Time           `json:"created_at"`
	HasPetrol          bool                `json:"has_petrol"`
	HasDiesel          bool                `json:"has_diesel"`
	HasCng             bool                `json:"has_cng"`
	HasElectric        bool                `json:"has_electric"`
	VariantCount       int32               `json:"variant_count"`
}

type CarPowertrainsElectric struct {
	ID                        int32               `json:"id"`
	VariantID                 int32               `json:"variant_id"`
	NumMotors                 *int32              `json:"num_motors"`
	MotorType                 *string             `json:"motor_type"`
	BatteryCapacity           decimal.NullDecimal `json:"battery_capacity"`
	BatteryChemistry          *string             `json:"battery_chemistry"`
	ThermalManagementSystem   *string             `json:"thermal_management_system"`
	DrivetrainID              *int32              `json:"drivetrain_id"`
	PowerPs                   *int32              `json:"power_ps"`
	TorqueNm                  *int32              `json:"torque_nm"`
	ClaimedRange              *int32              `json:"claimed_range"`
	RealWorldRange            *int32              `json:"real_world_range"`
	TopSpeedKmph              *int32              `json:"top_speed_kmph"`
	TopSpeedTimeSec           decimal.NullDecimal `json:"top_speed_time_sec"`
	AcChargingOutput          decimal.NullDecimal `json:"ac_charging_output"`
	AcChargingTime            decimal.NullDecimal `json:"ac_charging_time"`
	DcChargingOutput          decimal.NullDecimal `json:"dc_charging_output"`
	DcFastChargingTime        *string             `json:"dc_fast_charging_time"`
	BatteryWarrantyKm         *int32              `json:"battery_warranty_km"`
	BatteryWarrantyYears      *int32              `json:"battery_warranty_years"`
	MotorWarrantyKm           *int32              `json:"motor_warranty_km"`
	MotorWarrantyYears        *int32              `json:"motor_warranty_years"`
	StandardWarrantyKm        *string             `json:"standard_warranty_km"`
	StandardWarrantyYears     *int32              `json:"standard_warranty_years"`
	IsDefault                 bool                `json:"is_default"`
	IsDeleted                 bool                `json:"is_deleted"`
	DeletedBy                 *int32              `json:"deleted_by"`
	DeletedAt                 *time.Time          `json:"deleted_at"`
	ExpiresAt                 *time.Time          `json:"expires_at"`
	CreatedAt                 time.Time           `json:"created_at"`
	ChargingOptionsRaw        *string             `json:"charging_options_raw"`
	ChargingPort              *string             `json:"charging_port"`
	EmissionNormCompliance    *string             `json:"emission_norm_compliance"`
	MotorPowerKw              decimal.NullDecimal `json:"motor_power_kw"`
	RegenerativeBraking       bool                `json:"regenerative_braking"`
	RegenerativeBrakingLevels *int32              `json:"regenerative_braking_levels"`
}

type CarPowertrainsIce struct {
	ID                     int32               `json:"id"`
	VariantID              int32               `json:"variant_id"`
	FuelType               int32               `json:"fuel_type"`
	FuelTypeSubCategory    *string             `json:"fuel_type_sub_category"`
	FuelTankCapacity       decimal.NullDecimal `json:"fuel_tank_capacity"`
	CngTankCapacity        decimal.NullDecimal `json:"cng_tank_capacity"`
	KerbWeight             *int32              `json:"kerb_weight"`
	EngineDisplacement     decimal.NullDecimal `json:"engine_displacement"`
	CubicCapacity          *int32              `json:"cubic_capacity"`
	Cylinders              *int32              `json:"cylinders"`
	NumGears               *int32              `json:"num_gears"`
	IsFourByFour           bool                `json:"is_four_by_four"`
	DrivetrainID           *int32              `json:"drivetrain_id"`
	PowerPs                *int32              `json:"power_ps"`
	PowerMinRpm            *int32              `json:"power_min_rpm"`
	PowerMaxRpm            *int32              `json:"power_max_rpm"`
	TorqueNm               *int32              `json:"torque_nm"`
	TorqueMinRpm           *int32              `json:"torque_min_rpm"`
	TorqueMaxRpm           *int32              `json:"torque_max_rpm"`
	ClaimedFe              decimal.NullDecimal `json:"claimed_fe"`
	RealWorldMileage       decimal.NullDecimal `json:"real_world_mileage"`
	TopSpeedKmph           *int32              `json:"top_speed_kmph"`
	TopSpeedTimeSec        decimal.NullDecimal `json:"top_speed_time_sec"`
	IsDefault              bool                `json:"is_default"`
	IsDeleted              bool                `json:"is_deleted"`
	DeletedBy              *int32              `json:"deleted_by"`
	DeletedAt              *time.Time          `json:"deleted_at"`
	ExpiresAt              *time.Time          `json:"expires_at"`
	CreatedAt              time.Time           `json:"created_at"`
	EmissionNormCompliance *string             `json:"emission_norm_compliance"`
	TurboCharger           bool                `json:"turbo_charger"`
}

type CarVariant struct {
	ID                int32           `json:"id"`
	ModelID           int32           `json:"model_id"`
	VariantName       string          `json:"variant_name"`
	Price             decimal.Decimal `json:"price"`
	SeatingCapacity   int32           `json:"seating_capacity"`
	TransmissionID    int32           `json:"transmission_id"`
	IsTopSeller       bool            `json:"is_top_seller"`
	CreatedAt         time.Time       `json:"created_at"`
	BootSpaceLitres   *int32          `json:"boot_space_litres"`
	FrontBrakeType    *string         `json:"front_brake_type"`
	FrontSuspension   *string         `json:"front_suspension"`
	GroundClearanceMm *int32          `json:"ground_clearance_mm"`
	HeightMm          *int32          `json:"height_mm"`
	LengthMm          *int32          `json:"length_mm"`
	RearBrakeType     *string         `json:"rear_brake_type"`
	RearSuspension    *string         `json:"rear_suspension"`
	SteeringType      *string         `json:"steering_type"`
	WheelBaseMm       *int32          `json:"wheel_base_mm"`
	WidthMm           *int32          `json:"width_mm"`
}

type City struct {
	ID               int32   `json:"id"`
	Name             string  `json:"name"`
	Slug             string  `json:"slug"`
	IsMetro          bool    `json:"is_metro"`
	IsTopCity        bool    `json:"is_top_city"`
	IsSellCarEnabled bool    `json:"is_sell_car_enabled"`
	LogoUrl          *string `json:"logo_url"`
	StateID          int32   `json:"state_id"`
}

type Country struct {
	ID             int32               `json:"id"`
	Name           string              `json:"name"`
	Code           string              `json:"code"`
	Currency       *string             `json:"currency"`
	CurrencySymbol *string             `json:"currency_symbol"`
	CurrencyCode   *string             `json:"currency_code"`
	ExchangeRate   decimal.NullDecimal `json:"exchange_rate"`
	DistanceUnit   *string             `json:"distance_unit"`
	FuelUnit       *string             `json:"fuel_unit"`
	IsActive       bool                `json:"is_active"`
}

type Feature struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	CategoryID *int32    `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type FeatureCategory struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type FuelPrice struct {
	ID           int64           `json:"id"`
	CityID       int32           `json:"city_id"`
	FuelType     int16           `json:"fuel_type"`
	Price        decimal.Decimal `json:"price"`
	PriceChange  decimal.Decimal `json:"price_change"`
	ApplicableOn time.Time       `json:"applicable_on"`
	CreatedAt    time.Time       `json:"created_at"`
}

type InsuranceLead struct {
	ID                      int32      `json:"id"`
	UserID                  *int32     `json:"user_id"`
	Name                    *string    `json:"name"`
	Mobile                  string     `json:"mobile"`
	BrandID                 *int32     `json:"brand_id"`
	ModelID                 *int32     `json:"model_id"`
	RegistrationNumber      *string    `json:"registration_number"`
	CityID                  *int32     `json:"city_id"`
	Status                  string     `json:"status"`
	LeadChannel             *string    `json:"lead_channel"`
	UtmSource               *string    `json:"utm_source"`
	UtmMedium               *string    `json:"utm_medium"`
	UtmCampaign             *string    `json:"utm_campaign"`
	LandingPage             *string    `json:"landing_page"`
	DeviceType              *string    `json:"device_type"`
	IpAddress               *string    `json:"ip_address"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
	CurrentInsuranceCompany *string    `json:"current_insurance_company"`
	HadClaim                *bool      `json:"had_claim"`
	InsuranceType           *string    `json:"insurance_type"`
	PolicyExpiryDate        *time.Time `json:"policy_expiry_date"`
	RegistrationStateID     *int32     `json:"registration_state_id"`
	RegistrationYear        *int32     `json:"registration_year"`
	VariantID               *int32     `json:"variant_id"`
}

type LeadActivity struct {
	ID           int64     `json:"id"`
	LeadType     string    `json:"lead_type"`
	LeadID       int32     `json:"lead_id"`
	AdminID      int32     `json:"admin_id"`
	ActivityType *string   `json:"activity_type"`
	Notes        *string   `json:"notes"`
	CreatedAt    time.Time `json:"created_at"`
}

type Lender struct {
	ID              int32               `json:"id"`
	Name            string              `json:"name"`
	LogoUrl         *string             `json:"logo_url"`
	MinInterestRate decimal.NullDecimal `json:"min_interest_rate"`
	IsActive        bool                `json:"is_active"`
	CreatedAt       time.Time           `json:"created_at"`
	CreatedBy       *int32              `json:"created_by"`
	MaxInterestRate decimal.NullDecimal `json:"max_interest_rate"`
	MaxLoanAmount   decimal.NullDecimal `json:"max_loan_amount"`
	MaxTenureYears  *int32              `json:"max_tenure_years"`
	UpdatedAt       time.Time           `json:"updated_at"`
	UpdatedBy       *int32              `json:"updated_by"`
}

type LoanLead struct {
	ID            int32               `json:"id"`
	UserID        *int32              `json:"user_id"`
	Name          *string             `json:"name"`
	Mobile        string              `json:"mobile"`
	BrandID       *int32              `json:"brand_id"`
	ModelID       *int32              `json:"model_id"`
	LenderID      *int32              `json:"lender_id"`
	LoanAmount    decimal.NullDecimal `json:"loan_amount"`
	TenureYears   *int32              `json:"tenure_years"`
	MonthlyIncome decimal.NullDecimal `json:"monthly_income"`
	Status        string              `json:"status"`
	LeadChannel   *string             `json:"lead_channel"`
	UtmSource     *string             `json:"utm_source"`
	UtmMedium     *string             `json:"utm_medium"`
	UtmCampaign   *string             `json:"utm_campaign"`
	LandingPage   *string             `json:"landing_page"`
	DeviceType    *string             `json:"device_type"`
	IpAddress     *string             `json:"ip_address"`
	CreatedAt     time.Time           `json:"created_at"`
	InterestRate  decimal.NullDecimal `json:"interest_rate"`
	UpdatedAt     time.Time           `json:"updated_at"`
	VariantID     *int32              `json:"variant_id"`
}

type MileageLog struct {
	ID              int32               `json:"id"`
	UserID          int32               `json:"user_id"`
	ModelID         *int32              `json:"model_id"`
	Odometer        int32               `json:"odometer"`
	FuelFilled      decimal.Decimal     `json:"fuel_filled"`
	DistanceCovered *int32              `json:"distance_covered"`
	MileageResult   decimal.NullDecimal `json:"mileage_result"`
	LoggedAt        time.Time           `json:"logged_at"`
	CreatedAt       time.Time           `json:"created_at"`
}

type NewCarOffer struct {
	ID          int32               `json:"id"`
	ModelID     int32               `json:"model_id"`
	VariantID   *int32              `json:"variant_id"`
	CityID      *int32              `json:"city_id"`
	OfferType   *int32              `json:"offer_type"`
	OfferAmount decimal.NullDecimal `json:"offer_amount"`
	Description *string             `json:"description"`
	ValidFrom   *time.Time          `json:"valid_from"`
	ValidUntil  *time.Time          `json:"valid_until"`
	IsActive    bool                `json:"is_active"`
	ImageUrl    string              `json:"image_url"`
}

type Notification struct {
	ID            int64      `json:"id"`
	UserID        int32      `json:"user_id"`
	Title         *string    `json:"title"`
	Message       *string    `json:"message"`
	Type          *string    `json:"type"`
	ReferenceType *string    `json:"reference_type"`
	ReferenceID   *int32     `json:"reference_id"`
	IsRead        bool       `json:"is_read"`
	ReadAt        *time.Time `json:"read_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type PageView struct {
	ID         int64     `json:"id"`
	PageType   *string   `json:"page_type"`
	PageID     *int32    `json:"page_id"`
	UserID     *int32    `json:"user_id"`
	PageUrl    *string   `json:"page_url"`
	DeviceType *string   `json:"device_type"`
	IpAddress  *string   `json:"ip_address"`
	ViewedAt   time.Time `json:"viewed_at"`
}

type Permission struct {
	ID            int32  `json:"id"`
	Module        string `json:"module"`
	Action        string `json:"action"`
	PermissionKey string `json:"permission_key"`
}

type PriceDropAlertLead struct {
	ID                  int32               `json:"id"`
	UserID              *int32              `json:"user_id"`
	Mobile              string              `json:"mobile"`
	Email               *string             `json:"email"`
	BrandID             *int32              `json:"brand_id"`
	ModelID             *int32              `json:"model_id"`
	AlertType           *string             `json:"alert_type"`
	IsActive            bool                `json:"is_active"`
	NotifiedAt          *time.Time          `json:"notified_at"`
	LeadChannel         *string             `json:"lead_channel"`
	UtmSource           *string             `json:"utm_source"`
	UtmMedium           *string             `json:"utm_medium"`
	UtmCampaign         *string             `json:"utm_campaign"`
	LandingPage         *string             `json:"landing_page"`
	DeviceType          *string             `json:"device_type"`
	IpAddress           *string             `json:"ip_address"`
	CreatedAt           time.Time           `json:"created_at"`
	PriceAtSubscription decimal.NullDecimal `json:"price_at_subscription"`
	UpdatedAt           time.Time           `json:"updated_at"`
}

type PrismaMigration struct {
	ID                string             `json:"id"`
	Checksum          string             `json:"checksum"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	MigrationName     string             `json:"migration_name"`
	Logs              *string            `json:"logs"`
	RolledBackAt      pgtype.Timestamptz `json:"rolled_back_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	AppliedStepsCount int32              `json:"applied_steps_count"`
}

type Review struct {
	ID                int32               `json:"id"`
	UserID            int32               `json:"user_id"`
	ModelID           int32               `json:"model_id"`
	VariantID         *int32              `json:"variant_id"`
	Rating            decimal.NullDecimal `json:"rating"`
	Title             *string             `json:"title"`
	Body              *string             `json:"body"`
	OwnershipDuration *string             `json:"ownership_duration"`
	KmDriven          *int32              `json:"km_driven"`
	IsVerifiedOwner   bool                `json:"is_verified_owner"`
	Status            string              `json:"status"`
	RejectedReason    *string             `json:"rejected_reason"`
	HelpfulCount      int32               `json:"helpful_count"`
	CreatedAt         time.Time           `json:"created_at"`
}

type ReviewCategoryScore struct {
	ID       int32               `json:"id"`
	ReviewID int32               `json:"review_id"`
	Category *string             `json:"category"`
	Score    decimal.NullDecimal `json:"score"`
}

type ReviewHelpfulVote struct {
	ID        int32     `json:"id"`
	ReviewID  int32     `json:"review_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ReviewImage struct {
	ID       int32  `json:"id"`
	ReviewID int32  `json:"review_id"`
	ImageUrl string `json:"image_url"`
}

type ReviewReply struct {
	ID        int32     `json:"id"`
	ReviewID  int32     `json:"review_id"`
	UserID    *int32    `json:"user_id"`
	AdminID   *int32    `json:"admin_id"`
	Body      string    `json:"body"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Role struct {
	ID           int32     `json:"id"`
	RoleName     string    `json:"role_name"`
	ParentRoleID *int32    `json:"parent_role_id"`
	CreatedBy    *int32    `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type SearchLog struct {
	ID           int64     `json:"id"`
	UserID       *int32    `json:"user_id"`
	SearchQuery  *string   `json:"search_query"`
	ResultsCount *int32    `json:"results_count"`
	PageUrl      *string   `json:"page_url"`
	DeviceType   *string   `json:"device_type"`
	IpAddress    *string   `json:"ip_address"`
	CreatedAt    time.Time `json:"created_at"`
	SessionID    *string   `json:"session_id"`
	UserAgent    *string   `json:"user_agent"`
}

type SellCarLead struct {
	ID          int32     `json:"id"`
	UserID      *int32    `json:"user_id"`
	Name        *string   `json:"name"`
	Mobile      string    `json:"mobile"`
	BrandID     *int32    `json:"brand_id"`
	ModelID     *int32    `json:"model_id"`
	Year        *int32    `json:"year"`
	KmDriven    *int32    `json:"km_driven"`
	CityID      *int32    `json:"city_id"`
	Status      string    `json:"status"`
	LeadChannel *string   `json:"lead_channel"`
	UtmSource   *string   `json:"utm_source"`
	UtmMedium   *string   `json:"utm_medium"`
	UtmCampaign *string   `json:"utm_campaign"`
	LandingPage *string   `json:"landing_page"`
	DeviceType  *string   `json:"device_type"`
	IpAddress   *string   `json:"ip_address"`
	CreatedAt   time.Time `json:"created_at"`
}

type SeoMetum struct {
	ID               int32     `json:"id"`
	StaticPageSlug   *string   `json:"static_page_slug"`
	MetaTitle        *string   `json:"meta_title"`
	MetaDescription  *string   `json:"meta_description"`
	MetaKeywords     *string   `json:"meta_keywords"`
	CanonicalUrl     *string   `json:"canonical_url"`
	UpdatedBy        *int32    `json:"updated_by"`
	UpdatedAt        time.Time `json:"updated_at"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedBy        *int32    `json:"created_by"`
	EntityID         *int32    `json:"entity_id"`
	H1Tag            *string   `json:"h1_tag"`
	OgDescription    *string   `json:"og_description"`
	OgImage          *string   `json:"og_image"`
	OgTitle          *string   `json:"og_title"`
	RobotsMeta       *string   `json:"robots_meta"`
	Status           bool      `json:"status"`
	PageType         int32     `json:"page_type"`
	ArticleSchema    *string   `json:"article_schema"`
	AuthorSchema     *string   `json:"author_schema"`
	BreadcrumbSchema *string   `json:"breadcrumb_schema"`
	FaqSchema        *string   `json:"faq_schema"`
	ReviewSchema     *string   `json:"review_schema"`
	VehicleSchema    *string   `json:"vehicle_schema"`
}

type SeoRedirect struct {
	ID           int32     `json:"id"`
	OldPath      string    `json:"old_path"`
	NewPath      string    `json:"new_path"`
	RedirectType int32     `json:"redirect_type"`
	IsActive     bool      `json:"is_active"`
	CreatedBy    *int32    `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type SiteSetting struct {
	ID                 int32      `json:"id"`
	MaintenanceMode    bool       `json:"maintenance_mode"`
	MaintenanceMessage *string    `json:"maintenance_message"`
	SupportEmail       *string    `json:"support_email"`
	ContactEmail       *string    `json:"contact_email"`
	ContactNumber      *string    `json:"contact_number"`
	WhatsappNumber     *string    `json:"whatsapp_number"`
	Address            *string    `json:"address"`
	FacebookUrl        *string    `json:"facebook_url"`
	InstagramUrl       *string    `json:"instagram_url"`
	TwitterUrl         *string    `json:"twitter_url"`
	YoutubeUrl         *string    `json:"youtube_url"`
	LinkedinUrl        *string    `json:"linkedin_url"`
	CreatedBy          int32      `json:"created_by"`
	UpdatedBy          int32      `json:"updated_by"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}

type SitemapEntry struct {
	ID              int32               `json:"id"`
	PageType        string              `json:"page_type"`
	PageID          *int32              `json:"page_id"`
	UrlPath         string              `json:"url_path"`
	Priority        decimal.NullDecimal `json:"priority"`
	ChangeFrequency *string             `json:"change_frequency"`
	IsIncluded      bool                `json:"is_included"`
	LastModified    *time.Time          `json:"last_modified"`
}

type SoftLead struct {
	ID             int32     `json:"id"`
	UserID         *int32    `json:"user_id"`
	Mobile         *string   `json:"mobile"`
	BrandID        *int32    `json:"brand_id"`
	ModelID        *int32    `json:"model_id"`
	CalculatorType *string   `json:"calculator_type"`
	InputSummary   *string   `json:"input_summary"`
	Status         string    `json:"status"`
	LeadChannel    *string   `json:"lead_channel"`
	CreatedAt      time.Time `json:"created_at"`
	DeviceType     *string   `json:"device_type"`
	IpAddress      *string   `json:"ip_address"`
	LandingPage    *string   `json:"landing_page"`
	UpdatedAt      time.Time `json:"updated_at"`
	UtmCampaign    *string   `json:"utm_campaign"`
	UtmMedium      *string   `json:"utm_medium"`
	UtmSource      *string   `json:"utm_source"`
}

type State struct {
	ID        int32   `json:"id"`
	CountryID int32   `json:"country_id"`
	Name      string  `json:"name"`
	Code      *string `json:"code"`
}

type StoryGroup struct {
	ID             int32      `json:"id"`
	Title          string     `json:"title"`
	CoverMediaType string     `json:"cover_media_type"`
	CoverMediaUrl  string     `json:"cover_media_url"`
	ViewCount      int32      `json:"view_count"`
	IsActive       bool       `json:"is_active"`
	DisplayOrder   int32      `json:"display_order"`
	CreatedBy      *int32     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedBy      *int32     `json:"updated_by"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

type StoryItem struct {
	ID           int32      `json:"id"`
	GroupID      int32      `json:"group_id"`
	MediaType    string     `json:"media_type"`
	MediaUrl     string     `json:"media_url"`
	Description  *string    `json:"description"`
	Link         *string    `json:"link"`
	ViewCount    int32      `json:"view_count"`
	DisplayOrder int32      `json:"display_order"`
	CreatedBy    *int32     `json:"created_by"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedBy    *int32     `json:"updated_by"`
	UpdatedAt    *time.Time `json:"updated_at"`
	EndAt        *time.Time `json:"end_at"`
	StartAt      *time.Time `json:"start_at"`
	Status       string     `json:"status"`
}

type Testimonial struct {
	ID             int32               `json:"id"`
	UserID         *int32              `json:"user_id"`
	CustomerName   string              `json:"customer_name"`
	CustomerCity   *string             `json:"customer_city"`
	PhotoUrl       *string             `json:"photo_url"`
	Rating         decimal.NullDecimal `json:"rating"`
	Quote          string              `json:"quote"`
	Status         string              `json:"status"`
	RejectedReason *string             `json:"rejected_reason"`
	ReviewedBy     *int32              `json:"reviewed_by"`
	ReviewedAt     *time.Time          `json:"reviewed_at"`
	DisplayOrder   int32               `json:"display_order"`
	IsActive       bool                `json:"is_active"`
	CreatedBy      *int32              `json:"created_by"`
	CreatedAt      time.Time           `json:"created_at"`
}

type UsedCarListing struct {
	ID                  int32               `json:"id"`
	SellerID            int32               `json:"seller_id"`
	ModelID             int32               `json:"model_id"`
	VariantID           *int32              `json:"variant_id"`
	PowertrainType      *string             `json:"powertrain_type"`
	PowertrainID        *int32              `json:"powertrain_id"`
	Year                *int32              `json:"year"`
	RegistrationNumber  *string             `json:"registration_number"`
	KmDriven            *int32              `json:"km_driven"`
	OwnerCount          *int32              `json:"owner_count"`
	Color               *string             `json:"color"`
	Price               decimal.NullDecimal `json:"price"`
	CityID              int32               `json:"city_id"`
	InsuranceValidTill  *time.Time          `json:"insurance_valid_till"`
	IsInspected         bool                `json:"is_inspected"`
	InspectionReportUrl *string             `json:"inspection_report_url"`
	Status              string              `json:"status"`
	CreatedAt           time.Time           `json:"created_at"`
}

type UsedCarListingImage struct {
	ID        int32  `json:"id"`
	ListingID int32  `json:"listing_id"`
	ImageUrl  string `json:"image_url"`
	IsPrimary bool   `json:"is_primary"`
}

type User struct {
	ID                  int32      `json:"id"`
	Name                string     `json:"name"`
	Email               *string    `json:"email"`
	Mobile              string     `json:"mobile"`
	PasswordHash        *string    `json:"password_hash"`
	CityID              *int32     `json:"city_id"`
	IsVerified          bool       `json:"is_verified"`
	Status              string     `json:"status"`
	FailedLoginAttempts int32      `json:"failed_login_attempts"`
	IsLocked            bool       `json:"is_locked"`
	LockedAt            *time.Time `json:"locked_at"`
	LockedReason        *string    `json:"locked_reason"`
	LastLoginAt         *time.Time `json:"last_login_at"`
	LastLoginIp         *string    `json:"last_login_ip"`
	CreatedAt           time.Time  `json:"created_at"`
}

type UserAddress struct {
	ID           int32     `json:"id"`
	UserID       int32     `json:"user_id"`
	AddressType  *string   `json:"address_type"`
	AddressLine1 *string   `json:"address_line1"`
	AddressLine2 *string   `json:"address_line2"`
	CityID       int32     `json:"city_id"`
	Pincode      *string   `json:"pincode"`
	IsDefault    bool      `json:"is_default"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserOtpVerification struct {
	ID         int32      `json:"id"`
	Mobile     string     `json:"mobile"`
	OtpCode    string     `json:"otp_code"`
	Purpose    string     `json:"purpose"`
	IpAddress  *string    `json:"ip_address"`
	ExpiresAt  time.Time  `json:"expires_at"`
	VerifiedAt *time.Time `json:"verified_at"`
	CreatedAt  time.Time  `json:"created_at"`
	Email      *string    `json:"email"`
}

type VariantFeature struct {
	ID        int32     `json:"id"`
	VariantID int32     `json:"variant_id"`
	FeatureID int32     `json:"feature_id"`
	Value     *string   `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}
