// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countModelReviews = `-- name: CountModelReviews :one
SELECT count(*) FROM reviews WHERE model_id = $1 AND status = 'approved'
`

func (q *Queries) CountModelReviews(ctx context.Context, modelID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countModelReviews, modelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listModelReviews = `-- name: ListModelReviews :many
SELECT r.id, r.user_id, u.name AS user_name,
       r.variant_id, v.variant_name,
       r.rating, r.title, r.body,
       r.ownership_duration, r.km_driven, r.is_verified_owner,
       r.helpful_count, r.created_at
FROM reviews r
JOIN users u ON u.id = r.user_id
LEFT JOIN car_variants v ON v.id = r.variant_id
WHERE r.model_id = $1 AND r.status = 'approved'
ORDER BY
  CASE WHEN $2::text = 'helpfulCount' AND $3::text = 'asc'  THEN r.helpful_count END ASC,
  CASE WHEN $2::text = 'helpfulCount' AND $3::text = 'desc' THEN r.helpful_count END DESC,
  CASE WHEN $2::text = 'rating'       AND $3::text = 'asc'  THEN r.rating END ASC,
  CASE WHEN $2::text = 'rating'       AND $3::text = 'desc' THEN r.rating END DESC,
  CASE WHEN $3::text = 'asc' THEN r.created_at END ASC,
  r.created_at DESC
LIMIT $5 OFFSET $4
`

type ListModelReviewsParams struct {
	ModelID   int32  `json:"model_id"`
	SortBy    string `json:"sort_by"`
	SortDir   string `json:"sort_dir"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListModelReviewsRow struct {
	ID                int32               `json:"id"`
	UserID            int32               `json:"user_id"`
	UserName          string              `json:"user_name"`
	VariantID         *int32              `json:"variant_id"`
	VariantName       *string             `json:"variant_name"`
	Rating            decimal.NullDecimal `json:"rating"`
	Title             *string             `json:"title"`
	Body              *string             `json:"body"`
	OwnershipDuration *string             `json:"ownership_duration"`
	KmDriven          *int32              `json:"km_driven"`
	IsVerifiedOwner   bool                `json:"is_verified_owner"`
	HelpfulCount      int32               `json:"helpful_count"`
	CreatedAt         time.Time           `json:"created_at"`
}

// Approved reviews only: this is the public feed, never a preview of
// pending or rejected content.
//
// Sort is applied here rather than in Go because it decides which page of
// rows comes back at all. Only the two columns the API exposes are
// accepted, matched by name, so the ordering can never be driven by
// caller-supplied SQL.
func (q *Queries) ListModelReviews(ctx context.Context, arg ListModelReviewsParams) ([]ListModelReviewsRow, error) {
	rows, err := q.db.Query(ctx, listModelReviews,
		arg.ModelID,
		arg.SortBy,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelReviewsRow{}
	for rows.Next() {
		var i ListModelReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.VariantID,
			&i.VariantName,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.OwnershipDuration,
			&i.KmDriven,
			&i.IsVerifiedOwner,
			&i.HelpfulCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelAverageRating = `-- name: ModelAverageRating :one
SELECT COALESCE(avg(r.rating), 0)::numeric AS avg_rating
FROM reviews r
WHERE r.model_id = $1 AND r.status = 'approved' AND r.rating IS NOT NULL
`

// Kept separate from the breakdown: averaging across grouped rows would
// weight each star equally instead of each review.
// COALESCE keeps the scan off a NULL for a model with no ratings; the
// caller uses the review count to decide whether to report an average.
func (q *Queries) ModelAverageRating(ctx context.Context, modelID int32) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, modelAverageRating, modelID)
	var avg_rating decimal.Decimal
	err := row.Scan(&avg_rating)
	return avg_rating, err
}

const modelRatingBreakdown = `-- name: ModelRatingBreakdown :many
SELECT round(r.rating)::int AS star, count(*)::bigint AS count
FROM reviews r
WHERE r.model_id = $1 AND r.status = 'approved' AND r.rating IS NOT NULL
GROUP BY round(r.rating)
`

type ModelRatingBreakdownRow struct {
	Star  int32 `json:"star"`
	Count int64 `json:"count"`
}

// Star counts for the bar chart, computed in SQL so the rows fetched do
// not grow with how many reviews a model has.
func (q *Queries) ModelRatingBreakdown(ctx context.Context, modelID int32) ([]ModelRatingBreakdownRow, error) {
	rows, err := q.db.Query(ctx, modelRatingBreakdown, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRatingBreakdownRow{}
	for rows.Next() {
		var i ModelRatingBreakdownRow
		if err := rows.Scan(&i.Star, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewCategoryScoresFor = `-- name: ReviewCategoryScoresFor :many
SELECT s.review_id, s.category, s.score
FROM review_category_scores s
WHERE s.review_id = ANY($1::int[])
`

type ReviewCategoryScoresForRow struct {
	ReviewID int32               `json:"review_id"`
	Category *string             `json:"category"`
	Score    decimal.NullDecimal `json:"score"`
}

func (q *Queries) ReviewCategoryScoresFor(ctx context.Context, reviewIds []int32) ([]ReviewCategoryScoresForRow, error) {
	rows, err := q.db.Query(ctx, reviewCategoryScoresFor, reviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewCategoryScoresForRow{}
	for rows.Next() {
		var i ReviewCategoryScoresForRow
		if err := rows.Scan(&i.ReviewID, &i.Category, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewImagesFor = `-- name: ReviewImagesFor :many
SELECT i.review_id, i.id, i.image_url
FROM review_images i
WHERE i.review_id = ANY($1::int[])
ORDER BY i.id
`

type ReviewImagesForRow struct {
	ReviewID int32  `json:"review_id"`
	ID       int32  `json:"id"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) ReviewImagesFor(ctx context.Context, reviewIds []int32) ([]ReviewImagesForRow, error) {
	rows, err := q.db.Query(ctx, reviewImagesFor, reviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewImagesForRow{}
	for rows.Next() {
		var i ReviewImagesForRow
		if err := rows.Scan(&i.ReviewID, &i.ID, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewRepliesFor = `-- name: ReviewRepliesFor :many
SELECT p.review_id, p.id, p.body, p.created_at,
       p.user_id, u.name AS user_name,
       p.admin_id, a.name AS admin_name
FROM review_replies p
LEFT JOIN users u ON u.id = p.user_id
LEFT JOIN admin_users a ON a.id = p.admin_id
WHERE p.review_id = ANY($1::int[]) AND p.status = 'visible'
ORDER BY p.created_at ASC
`

type ReviewRepliesForRow struct {
	ReviewID  int32     `json:"review_id"`
	ID        int32     `json:"id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UserID    *int32    `json:"user_id"`
	UserName  *string   `json:"user_name"`
	AdminID   *int32    `json:"admin_id"`
	AdminName *string   `json:"admin_name"`
}

// Only replies still visible; a moderated-away reply never reaches the
// public response. A reply is authored either by a user or an admin.
func (q *Queries) ReviewRepliesFor(ctx context.Context, reviewIds []int32) ([]ReviewRepliesForRow, error) {
	rows, err := q.db.Query(ctx, reviewRepliesFor, reviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRepliesForRow{}
	for rows.Next() {
		var i ReviewRepliesForRow
		if err := rows.Scan(
			&i.ReviewID,
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UserID,
			&i.UserName,
			&i.AdminID,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewsMarkedHelpfulBy = `-- name: ReviewsMarkedHelpfulBy :many
SELECT h.review_id
FROM review_helpful_votes h
WHERE h.user_id = $1 AND h.review_id = ANY($2::int[])
`

type ReviewsMarkedHelpfulByParams struct {
	UserID    int32   `json:"user_id"`
	ReviewIds []int32 `json:"review_ids"`
}

func (q *Queries) ReviewsMarkedHelpfulBy(ctx context.Context, arg ReviewsMarkedHelpfulByParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, reviewsMarkedHelpfulBy, arg.UserID, arg.ReviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var review_id int32
		if err := rows.Scan(&review_id); err != nil {
			return nil, err
		}
		items = append(items, review_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
