// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: road_tax.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const roadTaxFixedChargesFor = `-- name: RoadTaxFixedChargesFor :one
SELECT f.registration, f.hsrp, f.fastag, f.hypothecation, f.source_url
FROM road_tax_fixed_charges f
LEFT JOIN states s ON s.id = f.state_id
WHERE f.state_id IS NULL OR s.slug = $1
ORDER BY (f.state_id IS NOT NULL) DESC, f.effective_from DESC
LIMIT 1
`

type RoadTaxFixedChargesForRow struct {
	Registration  decimal.Decimal `json:"registration"`
	Hsrp          decimal.Decimal `json:"hsrp"`
	Fastag        decimal.Decimal `json:"fastag"`
	Hypothecation decimal.Decimal `json:"hypothecation"`
	SourceUrl     *string         `json:"source_url"`
}

// State-specific charges when we hold them, otherwise the national row
// (state_id IS NULL) so a state we have not itemised still returns a total.
func (q *Queries) RoadTaxFixedChargesFor(ctx context.Context, slug string) (RoadTaxFixedChargesForRow, error) {
	row := q.db.QueryRow(ctx, roadTaxFixedChargesFor, slug)
	var i RoadTaxFixedChargesForRow
	err := row.Scan(
		&i.Registration,
		&i.Hsrp,
		&i.Fastag,
		&i.Hypothecation,
		&i.SourceUrl,
	)
	return i, err
}

const roadTaxRateFor = `-- name: RoadTaxRateFor :one
SELECT r.rate_pct,
       r.min_amount,
       r.basis,
       r.effective_from,
       r.source_url,
       r.verified
FROM road_tax_rates r
JOIN states s ON s.id = r.state_id
WHERE s.slug = $1
  AND r.effective_from <= CURRENT_DATE
  AND (r.fuel_type = $2 OR r.fuel_type IS NULL)
  AND (
        (r.basis = 'price'
           AND $3::numeric >= r.slab_min
           AND (r.slab_max IS NULL OR $3::numeric < r.slab_max))
     OR (r.basis = 'engine_cc'
           AND $4::numeric > 0
           AND $4::numeric >= r.slab_min
           AND (r.slab_max IS NULL OR $4::numeric < r.slab_max))
      )
ORDER BY (r.fuel_type IS NOT NULL) DESC, r.effective_from DESC
LIMIT 1
`

type RoadTaxRateForParams struct {
	Slug     string          `json:"slug"`
	FuelType *string         `json:"fuel_type"`
	Price    decimal.Decimal `json:"price"`
	EngineCc decimal.Decimal `json:"engine_cc"`
}

type RoadTaxRateForRow struct {
	RatePct       decimal.Decimal     `json:"rate_pct"`
	MinAmount     decimal.NullDecimal `json:"min_amount"`
	Basis         string              `json:"basis"`
	EffectiveFrom time.Time           `json:"effective_from"`
	SourceUrl     *string             `json:"source_url"`
	Verified      bool                `json:"verified"`
}

// The slab that applies to one car in one state.
//
// A row naming a fuel beats the catch-all row for that fuel, which is how
// an EV exemption overrides the state's general rate. Among equals the
// newest effective_from wins, so a rate change is a new row rather than an
// edit and the old figure stays auditable.
func (q *Queries) RoadTaxRateFor(ctx context.Context, arg RoadTaxRateForParams) (RoadTaxRateForRow, error) {
	row := q.db.QueryRow(ctx, roadTaxRateFor,
		arg.Slug,
		arg.FuelType,
		arg.Price,
		arg.EngineCc,
	)
	var i RoadTaxRateForRow
	err := row.Scan(
		&i.RatePct,
		&i.MinAmount,
		&i.Basis,
		&i.EffectiveFrom,
		&i.SourceUrl,
		&i.Verified,
	)
	return i, err
}

const roadTaxStateBySlug = `-- name: RoadTaxStateBySlug :one
SELECT s.id, s.name, s.slug
FROM states s
WHERE s.slug = $1
`

type RoadTaxStateBySlugRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) RoadTaxStateBySlug(ctx context.Context, slug string) (RoadTaxStateBySlugRow, error) {
	row := q.db.QueryRow(ctx, roadTaxStateBySlug, slug)
	var i RoadTaxStateBySlugRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const variantForOnRoad = `-- name: VariantForOnRoad :one
SELECT v.id,
       v.price,
       e.fuel_type AS ice_fuel_type,
       -- cubic_capacity is cc (216-6750); engine_displacement is litres
       -- (0.22-6.75). The cc-banded states slab on cc, so using the litre
       -- column would put every car in the lowest band.
       e.cubic_capacity,
       (el.variant_id IS NOT NULL)::boolean AS is_electric
FROM car_variants v
LEFT JOIN car_powertrains_ice e ON e.variant_id = v.id AND NOT e.is_deleted
LEFT JOIN car_powertrains_electric el ON el.variant_id = v.id AND NOT el.is_deleted
WHERE v.id = $1
`

type VariantForOnRoadRow struct {
	ID            int32           `json:"id"`
	Price         decimal.Decimal `json:"price"`
	IceFuelType   *int32          `json:"ice_fuel_type"`
	CubicCapacity *int32          `json:"cubic_capacity"`
	IsElectric    bool            `json:"is_electric"`
}

// Everything the on-road calculation needs about one variant: the price it
// is taxed on, the fuel that decides which slab applies, and the engine
// size for the states that band by displacement rather than price.
// fuel_type is the same 1/2/3 enum the fuel-price module uses; a row in
// car_powertrains_electric outranks it, since an EV has no ICE row.
func (q *Queries) VariantForOnRoad(ctx context.Context, id int32) (VariantForOnRoadRow, error) {
	row := q.db.QueryRow(ctx, variantForOnRoad, id)
	var i VariantForOnRoadRow
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.IceFuelType,
		&i.CubicCapacity,
		&i.IsElectric,
	)
	return i, err
}
