// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seo.sql

package store

import (
	"context"
)

const activeSeoRedirects = `-- name: ActiveSeoRedirects :many
SELECT old_path, new_path, redirect_type
FROM seo_redirects
WHERE is_active = true
ORDER BY created_at DESC
`

type ActiveSeoRedirectsRow struct {
	OldPath      string `json:"old_path"`
	NewPath      string `json:"new_path"`
	RedirectType int32  `json:"redirect_type"`
}

// The whole active list, not a per-path lookup. The website's proxy runs on
// every request and matches in memory; a query per request would put the
// database in front of every page load.
func (q *Queries) ActiveSeoRedirects(ctx context.Context) ([]ActiveSeoRedirectsRow, error) {
	rows, err := q.db.Query(ctx, activeSeoRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveSeoRedirectsRow{}
	for rows.Next() {
		var i ActiveSeoRedirectsRow
		if err := rows.Scan(&i.OldPath, &i.NewPath, &i.RedirectType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seoMetaForEntity = `-- name: SeoMetaForEntity :one
SELECT meta_title,
       meta_description,
       meta_keywords,
       canonical_url,
       h1_tag,
       og_title,
       og_description,
       og_image,
       robots_meta,
       vehicle_schema,
       review_schema,
       article_schema,
       author_schema,
       breadcrumb_schema
FROM seo_meta
WHERE page_type = $1
  AND status = true
  AND (entity_id = $2 OR entity_id IS NULL)
ORDER BY (entity_id IS NULL)
LIMIT 1
`

type SeoMetaForEntityParams struct {
	PageType int32  `json:"page_type"`
	EntityID *int32 `json:"entity_id"`
}

type SeoMetaForEntityRow struct {
	MetaTitle        *string `json:"meta_title"`
	MetaDescription  *string `json:"meta_description"`
	MetaKeywords     *string `json:"meta_keywords"`
	CanonicalUrl     *string `json:"canonical_url"`
	H1Tag            *string `json:"h1_tag"`
	OgTitle          *string `json:"og_title"`
	OgDescription    *string `json:"og_description"`
	OgImage          *string `json:"og_image"`
	RobotsMeta       *string `json:"robots_meta"`
	VehicleSchema    *string `json:"vehicle_schema"`
	ReviewSchema     *string `json:"review_schema"`
	ArticleSchema    *string `json:"article_schema"`
	AuthorSchema     *string `json:"author_schema"`
	BreadcrumbSchema *string `json:"breadcrumb_schema"`
}

// The row for one entity if an editor has written one, otherwise that page
// type's shared default template (entity_id IS NULL).
//
// One query rather than two round trips: ordering by whether entity_id is
// null puts the specific row first, so LIMIT 1 takes it when it exists and
// falls through to the template when it does not. A page should never ship
// with no title just because nobody has reached that entity yet.
func (q *Queries) SeoMetaForEntity(ctx context.Context, arg SeoMetaForEntityParams) (SeoMetaForEntityRow, error) {
	row := q.db.QueryRow(ctx, seoMetaForEntity, arg.PageType, arg.EntityID)
	var i SeoMetaForEntityRow
	err := row.Scan(
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CanonicalUrl,
		&i.H1Tag,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.RobotsMeta,
		&i.VehicleSchema,
		&i.ReviewSchema,
		&i.ArticleSchema,
		&i.AuthorSchema,
		&i.BreadcrumbSchema,
	)
	return i, err
}

const seoMetaForStaticPage = `-- name: SeoMetaForStaticPage :one
SELECT meta_title,
       meta_description,
       meta_keywords,
       canonical_url,
       h1_tag,
       og_title,
       og_description,
       og_image,
       robots_meta,
       vehicle_schema,
       review_schema,
       article_schema,
       author_schema,
       breadcrumb_schema
FROM seo_meta
WHERE page_type = $1
  AND static_page_slug = $2
  AND status = true
LIMIT 1
`

type SeoMetaForStaticPageParams struct {
	PageType       int32   `json:"page_type"`
	StaticPageSlug *string `json:"static_page_slug"`
}

type SeoMetaForStaticPageRow struct {
	MetaTitle        *string `json:"meta_title"`
	MetaDescription  *string `json:"meta_description"`
	MetaKeywords     *string `json:"meta_keywords"`
	CanonicalUrl     *string `json:"canonical_url"`
	H1Tag            *string `json:"h1_tag"`
	OgTitle          *string `json:"og_title"`
	OgDescription    *string `json:"og_description"`
	OgImage          *string `json:"og_image"`
	RobotsMeta       *string `json:"robots_meta"`
	VehicleSchema    *string `json:"vehicle_schema"`
	ReviewSchema     *string `json:"review_schema"`
	ArticleSchema    *string `json:"article_schema"`
	AuthorSchema     *string `json:"author_schema"`
	BreadcrumbSchema *string `json:"breadcrumb_schema"`
}

// Static pages are keyed by slug rather than entity id: there is no row in
// any table for "the home page", so the slug is the identity.
func (q *Queries) SeoMetaForStaticPage(ctx context.Context, arg SeoMetaForStaticPageParams) (SeoMetaForStaticPageRow, error) {
	row := q.db.QueryRow(ctx, seoMetaForStaticPage, arg.PageType, arg.StaticPageSlug)
	var i SeoMetaForStaticPageRow
	err := row.Scan(
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CanonicalUrl,
		&i.H1Tag,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.RobotsMeta,
		&i.VehicleSchema,
		&i.ReviewSchema,
		&i.ArticleSchema,
		&i.AuthorSchema,
		&i.BreadcrumbSchema,
	)
	return i, err
}
