// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usedcars.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const countUsedCarsByCity = `-- name: CountUsedCarsByCity :one
SELECT count(*) FROM used_car_listings
WHERE status = 'active' AND city_id = $1
`

func (q *Queries) CountUsedCarsByCity(ctx context.Context, cityID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUsedCarsByCity, cityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCityBySlug = `-- name: GetCityBySlug :one
SELECT id, name, slug FROM cities WHERE slug = $1 LIMIT 1
`

type GetCityBySlugRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetCityBySlug(ctx context.Context, slug string) (GetCityBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCityBySlug, slug)
	var i GetCityBySlugRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const listUsedCarsByCity = `-- name: ListUsedCarsByCity :many
SELECT l.id, l.price, l.year, l.km_driven, l.owner_count, l.is_inspected,
       m.name AS model_name, m.slug AS model_slug,
       b.name AS brand_name, b.slug AS brand_slug,
       img.image_url
FROM used_car_listings l
JOIN car_models m ON m.id = l.model_id
JOIN brands b ON b.id = m.brand_id
LEFT JOIN LATERAL (
    SELECT i.image_url
    FROM used_car_listing_images i
    WHERE i.listing_id = l.id
    ORDER BY i.is_primary DESC, i.id ASC
    LIMIT 1
) img ON true
WHERE l.status = 'active' AND l.city_id = $1
ORDER BY l.created_at DESC, l.id DESC
LIMIT $2
`

type ListUsedCarsByCityParams struct {
	CityID int32 `json:"city_id"`
	Limit  int32 `json:"limit"`
}

type ListUsedCarsByCityRow struct {
	ID          int32               `json:"id"`
	Price       decimal.NullDecimal `json:"price"`
	Year        *int32              `json:"year"`
	KmDriven    *int32              `json:"km_driven"`
	OwnerCount  *int32              `json:"owner_count"`
	IsInspected bool                `json:"is_inspected"`
	ModelName   string              `json:"model_name"`
	ModelSlug   string              `json:"model_slug"`
	BrandName   string              `json:"brand_name"`
	BrandSlug   string              `json:"brand_slug"`
	ImageUrl    string              `json:"image_url"`
}

// One row per listing with its primary image, resolved in a LATERAL so a
// listing with several images cannot multiply the result set.
func (q *Queries) ListUsedCarsByCity(ctx context.Context, arg ListUsedCarsByCityParams) ([]ListUsedCarsByCityRow, error) {
	rows, err := q.db.Query(ctx, listUsedCarsByCity, arg.CityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsedCarsByCityRow{}
	for rows.Next() {
		var i ListUsedCarsByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Price,
			&i.Year,
			&i.KmDriven,
			&i.OwnerCount,
			&i.IsInspected,
			&i.ModelName,
			&i.ModelSlug,
			&i.BrandName,
			&i.BrandSlug,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
