// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishlist.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const myWishlist = `-- name: MyWishlist :many
SELECT w.id, w.model_id, w.created_at,
       m.name, m.slug, m.launch_status, m.price_min, m.price_max, m.cover_image_url,
       b.id AS brand_id, b.name AS brand_name, b.slug AS brand_slug
FROM wishlists w
JOIN car_models m ON m.id = w.model_id
JOIN brands b ON b.id = m.brand_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type MyWishlistRow struct {
	ID            int32               `json:"id"`
	ModelID       int32               `json:"model_id"`
	CreatedAt     time.Time           `json:"created_at"`
	Name          string              `json:"name"`
	Slug          string              `json:"slug"`
	LaunchStatus  string              `json:"launch_status"`
	PriceMin      decimal.NullDecimal `json:"price_min"`
	PriceMax      decimal.NullDecimal `json:"price_max"`
	CoverImageUrl *string             `json:"cover_image_url"`
	BrandID       int32               `json:"brand_id"`
	BrandName     string              `json:"brand_name"`
	BrandSlug     string              `json:"brand_slug"`
}

// One visitor's saved models, newest first.
func (q *Queries) MyWishlist(ctx context.Context, userID int32) ([]MyWishlistRow, error) {
	rows, err := q.db.Query(ctx, myWishlist, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyWishlistRow{}
	for rows.Next() {
		var i MyWishlistRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.CreatedAt,
			&i.Name,
			&i.Slug,
			&i.LaunchStatus,
			&i.PriceMin,
			&i.PriceMax,
			&i.CoverImageUrl,
			&i.BrandID,
			&i.BrandName,
			&i.BrandSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wishlistAdd = `-- name: WishlistAdd :one
INSERT INTO wishlists (user_id, model_id, created_at)
VALUES ($1, $2, now())
RETURNING id
`

type WishlistAddParams struct {
	UserID  int32 `json:"user_id"`
	ModelID int32 `json:"model_id"`
}

func (q *Queries) WishlistAdd(ctx context.Context, arg WishlistAddParams) (int32, error) {
	row := q.db.QueryRow(ctx, wishlistAdd, arg.UserID, arg.ModelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const wishlistFind = `-- name: WishlistFind :one
SELECT id FROM wishlists WHERE user_id = $1 AND model_id = $2
`

type WishlistFindParams struct {
	UserID  int32 `json:"user_id"`
	ModelID int32 `json:"model_id"`
}

func (q *Queries) WishlistFind(ctx context.Context, arg WishlistFindParams) (int32, error) {
	row := q.db.QueryRow(ctx, wishlistFind, arg.UserID, arg.ModelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const wishlistRemove = `-- name: WishlistRemove :exec
DELETE FROM wishlists WHERE user_id = $1 AND model_id = $2
`

type WishlistRemoveParams struct {
	UserID  int32 `json:"user_id"`
	ModelID int32 `json:"model_id"`
}

func (q *Queries) WishlistRemove(ctx context.Context, arg WishlistRemoveParams) error {
	_, err := q.db.Exec(ctx, wishlistRemove, arg.UserID, arg.ModelID)
	return err
}
